DolphinQt: Make Windows tab bar scroll buttons opaque
dolphin-emu/dolphin pull request #10021
Opened 2021-08-11 18:56 UTC by Dentomologist

Fixes [12623](https://bugs.dolphin-emu.org/issues/12623).

2021-08-30 23:34 UTC, leoetlino requested changes

2021-08-30 23:34 UTC, leoetlino commented on Source/Core/DolphinQt/Settings.cpp
> +  QTabBar* const tab_bar = new QTabBar();
```suggestion
  auto* const tab_bar = new QTabBar();
```

2021-08-30 23:34 UTC, leoetlino commented on Source/Core/DolphinQt/Settings.cpp
> +  QToolButton* const tool_button = new QToolButton(tab_bar);
```suggestion
  auto* const tool_button = new QToolButton(tab_bar);
```

2021-08-30 23:34 UTC, leoetlino commented on Source/Core/DolphinQt/Settings.cpp
> +  const Common::ScopeGuard delete_widgets([&tab_bar]() { delete tab_bar; });
Consider using a unique_ptr for `tab_bar`.

2021-08-30 23:34 UTC, leoetlino commented on Source/Core/DolphinQt/Settings.cpp
> +      fmt::format("QTabBar QToolButton {{background-color: #{:08x}}};", background_color.rgba());
```suggestion
      fmt::format("QTabBar QToolButton {{ background-color: #{:08x}; }}", background_color.rgba());
```
for readability

2021-08-31 03:44 UTC, Dentomologist commented
@dolphin-emu-bot rebuild

2021-08-31 12:45 UTC, leoetlino requested changes

2021-08-31 12:45 UTC, leoetlino commented on Source/Core/DolphinQt/Settings.cpp
> +      fmt::format("QTabBar QToolButton {{ background-color: #{:08x}; }}", background_color);
`#include <fmt/format.h>` (sorry, missed this earlier)

2021-08-31 17:17 UTC, leoetlino approved these changes

2021-08-31 17:18 UTC, merged