VideoBackends / VideoCommon: expose ability to view shader/texture debug names
dolphin-emu/dolphin pull request #10065
Opened 2021-08-28 05:32 UTC by iwubcode

This gives the ability to view an application defined name for our Shaders/Textures in applications like RenderDoc.  Currently nothing takes advantage of this but a future feature will.  Breaking it out to make it easier to review.

2021-08-28 08:53 UTC, elsaxo commented
> This gives the ability to view an application defined name for our Shaders/Textures in applications like RenderDoc.  Currently nothing takes advantage of this but a future feature will.  Breaking it out to make it easier to review.

2021-08-29 04:37 UTC, iwubcode commented
I fixed most of the lint errors but one isn't matching my local formatting (I tried both clang-format 12.0.0 and 12.0.1).

2021-08-29 21:50 UTC, leoetlino commented
> I fixed most of the lint errors but the last error isn't matching my local formatting (I tried both clang-format 12.0.0 and 12.0.1).

Are you using Visual Studio's bundled copy of clang-format? If so, we should probably update our required clang-format version to 12...

2021-08-29 22:11 UTC, iwubcode commented
> Are you using Visual Studio's bundled copy of clang-format? If so, we should probably update our required clang-format version to 12...

Yeah I'm using VS bundled clang-format which is (12.0.0).  I thought maybe it was out of date so I grabbed the latest (12.0.1) from the prebuilt llvm release.  I didn't think about the version being too old!

2021-08-29 22:57 UTC, leoetlino requested changes
> Reviewed 32 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/10065)* status: all files reviewed, 6 unresolved discussions (waiting on @iwubcode)

___
*[Source/Core/VideoBackends/D3D/DXShader.h, line 7 at r1](https://reviewable.io/reviews/dolphin-emu/dolphin/10065#-MiJ3LPj6TSZwpDIm6ca:-MiJ3LPj6TSZwpDIm6cb:b-8w2ico) ([raw file](https://github.com/dolphin-emu/dolphin/blob/c308139b72a264eeb22dd6e264d83497f0db1a9e/Source/Core/VideoBackends/D3D/DXShader.h#L7)):*
> ```objc
> 
> #include <memory>
> #include <optional>
> ```

`<optional>`  seems to be unused
___
*[Source/Core/VideoBackends/D3D/DXShader.cpp, line 16 at r1](https://reviewable.io/reviews/dolphin-emu/dolphin/10065#-MiJ3U4ODw35XEXWrPfe:-MiJ3U4ODw35XEXWrPff:bpgb1oj) ([raw file](https://github.com/dolphin-emu/dolphin/blob/c308139b72a264eeb22dd6e264d83497f0db1a9e/Source/Core/VideoBackends/D3D/DXShader.cpp#L16)):*
> ```cpp
>   if (!name.empty())
>   {
>     m_shader->SetPrivateData(WKPDID_D3DDebugObjectName, static_cast<UINT>(name.size()),
> ```

For anyone wondering, SetPrivateData performs a copy of the string so there are no lifetime issues here.
___
*[Source/Core/VideoBackends/D3D/DXTexture.cpp, line 20 at r1](https://reviewable.io/reviews/dolphin-emu/dolphin/10065#-MiJ3x8f-rOA05suydwY:-MiJ3x8f-rOA05suydwZ:b-s9uw7l) ([raw file](https://github.com/dolphin-emu/dolphin/blob/c308139b72a264eeb22dd6e264d83497f0db1a9e/Source/Core/VideoBackends/D3D/DXTexture.cpp#L20)):*
> ```cpp
> DXTexture::DXTexture(const TextureConfig& config, ComPtr<ID3D11Texture2D> texture,
>                      std::string_view name)
>     : AbstractTexture(config), m_texture(std::move(texture)), m_name(name)
> ```

Just wondering, why do we need to store the name in this class (DXTexture) and not in DXShader?

Come to think of it, does SetPrivateData require that the name is null-terminated? If so, DXShader would have to store the name in a std::string to make sure it is null-terminated.
___
*[Source/Core/VideoBackends/OGL/OGLShader.h, line 20 at r1](https://reviewable.io/reviews/dolphin-emu/dolphin/10065#-MiJ4vKs1G_Aglz1BvbT:-MiJ4vKs1G_Aglz1BvbU:blns7hr) ([raw file](https://github.com/dolphin-emu/dolphin/blob/c308139b72a264eeb22dd6e264d83497f0db1a9e/Source/Core/VideoBackends/OGL/OGLShader.h#L20)):*
> ```objc
> public:
>   explicit OGLShader(ShaderStage stage, GLenum gl_type, GLuint gl_id, std::string source,
>                      std::string name);
> ```

`#include <string>`
___
*[Source/Core/VideoBackends/Software/SWRenderer.h, line 24 at r1](https://reviewable.io/reviews/dolphin-emu/dolphin/10065#-MiJ5bhh-v1g_HfUP-CK:-MiJ5bhh-v1g_HfUP-CL:b-kmvxcr) ([raw file](https://github.com/dolphin-emu/dolphin/blob/c308139b72a264eeb22dd6e264d83497f0db1a9e/Source/Core/VideoBackends/Software/SWRenderer.h#L24)):*
> ```objc
> 
>   std::unique_ptr<AbstractTexture> CreateTexture(const TextureConfig& config,
>                                                  std::string_view name) override;
> ```

missing include for string_view
___
*[Source/Core/VideoBackends/Vulkan/VKRenderer.h, line 39 at r1](https://reviewable.io/reviews/dolphin-emu/dolphin/10065#-MiJ5z0HBZvnbA6RehnX:-MiJ5z0HBZvnbA6RehnY:b-3d7l6l) ([raw file](https://github.com/dolphin-emu/dolphin/blob/c308139b72a264eeb22dd6e264d83497f0db1a9e/Source/Core/VideoBackends/Vulkan/VKRenderer.h#L39)):*
> ```objc
> 
>   std::unique_ptr<AbstractTexture> CreateTexture(const TextureConfig& config,
>                                                  std::string_view name) override;
> ```

include
___
*[Source/Core/VideoBackends/Vulkan/VKShader.cpp, line 63 at r1](https://reviewable.io/reviews/dolphin-emu/dolphin/10065#-MiJ6C1H3aS5PGZyUfFg:-MiJ6C1H3aS5PGZyUfFh:bwlb3ox) ([raw file](https://github.com/dolphin-emu/dolphin/blob/c308139b72a264eeb22dd6e264d83497f0db1a9e/Source/Core/VideoBackends/Vulkan/VKShader.cpp#L63)):*
According to Vulkan docs:

> VUID-VkDebugUtilsObjectNameInfoEXT-pObjectName-parameter
>
> If pObjectName is not NULL, pObjectName must be a null-terminated UTF-8 string

So it seems you need a std::string to ensure the name is null-terminated. The docs aren't clear about the required lifetime for the string you pass in though...


<!-- Sent from Reviewable.io -->

2021-08-30 05:28 UTC, iwubcode commented
Thank you @leoetlino for reviewing!  I'll admit, I didn't find a majority of the graphics api documentation very clear about lifetime requirements which is why I opted for the design I did.  Unfortunately, I guess I wasn't very thorough, so thank you for catching the issues you did :)

2021-08-30 12:30 UTC, leoetlino reviewed
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/10065)* status: all files reviewed, 2 unresolved discussions (waiting on @iwubcode)

___
*[Source/Core/VideoBackends/Vulkan/VKShader.cpp, line 21 at r2](https://reviewable.io/reviews/dolphin-emu/dolphin/10065#-MiM1QW88t0fQcXxhYL2:-MiM1QW88t0fQcXxhYL3:bwrios9) ([raw file](https://github.com/dolphin-emu/dolphin/blob/e1fbba571f9275e9a36d11f4bd8693ce40a5c483/Source/Core/VideoBackends/Vulkan/VKShader.cpp#L21)):*
> ```cpp
>   if (!m_name.empty())
>   {
>     VkDebugUtilsObjectNameInfoEXT nameInfo = {};
> ```

`name_info`
___
*[Source/Core/VideoBackends/Vulkan/VKShader.cpp, line 36 at r2](https://reviewable.io/reviews/dolphin-emu/dolphin/10065#-MiM1VugEhwz0ZGuyh1y:-MiM1VugEhwz0ZGuyh1z:bwrios9) ([raw file](https://github.com/dolphin-emu/dolphin/blob/e1fbba571f9275e9a36d11f4bd8693ce40a5c483/Source/Core/VideoBackends/Vulkan/VKShader.cpp#L36)):*
> ```cpp
>   if (!m_name.empty())
>   {
>     VkDebugUtilsObjectNameInfoEXT nameInfo = {};
> ```

`name_info`


<!-- Sent from Reviewable.io -->

2021-08-30 12:31 UTC, leoetlino commented
Rebasing should fix the lint failure

2021-08-30 18:59 UTC, leoetlino approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dolphin-emu/dolphin/10065)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iwubcode)



<!-- Sent from Reviewable.io -->

2021-08-30 19:00 UTC, merged

2021-08-31 02:01 UTC, iwubcode commented
Thanks @leoetlino for reviewing!

2022-01-01 17:35 UTC, elsaxo commented
> This gives the ability to view an application defined name for our Shaders/Textures in applications like RenderDoc. Currently nothing takes advantage of this but a future feature will. Breaking it out to make it easier to review.

2022-01-01 17:35 UTC, elsaxo commented
C