Resolve C++20 deprecation warnings
dolphin-emu/dolphin pull request #10949
Opened 2022-08-05 04:27 UTC by Zopolis4

Now that all builds are on C++20 a couple of new deprecation warnings are generated.

2022-08-05 10:27 UTC, phire requested changes

2022-08-05 10:27 UTC, phire commented on Source/Core/DolphinQt/Config/Graphics/AdvancedWidget.cpp
> +          [=, this](Core::State state) {
Nothing else seems to be captured by the `=`, it was only ever capturing `this`

You should get rid of the `=, `

The same appears to apply for most (if not all) of the following changes.

2022-08-05 20:16 UTC, Dentomologist commented on Source/Core/DolphinQt/MenuBar.cpp
> +          [=, this](Core::State state) { OnEmulationStateChanged(state); });
The lambda is unnecessary; we can replace it with `&MenuBar::OnEmulationStateChanged`.

2022-08-05 20:16 UTC, Dentomologist commented on Source/Core/DolphinQt/MainWindow.cpp
> +          });
We should create MainWindow::OnEmulationStateChange and put the contents of this lambda there.

2022-08-05 20:16 UTC, Dentomologist commented on Source/Core/DolphinQt/NetPlay/NetPlayDialog.cpp
> +          });
Extract lambda to new OnEmulationStateChange function

2022-08-08 02:08 UTC, phire approved these changes

2022-09-23 01:56 UTC, merged