MemoryViewWidget refactor memory table
dolphin-emu/dolphin pull request #11111
Opened 2022-10-01 00:16 UTC by TryTwo

Everything in the table was being re-created on every update. Future work needs the table to persist.

Add CreateTable() move all constants and semi-constants into it. It is called when the table size changes, font changes, or the displayed data type changes. 

Update() now updates address values and calls other update functions. Ideally it would only be called when addresses change (scroll, setting a different target address, etc) and after CreateTable(). Cleaning up update logic can be done in another PR, as it depends on MemoryWidget.

UpdateColumns() could be renamed to UpdateDataColumnValues() because it's for updating displayed memory values. This function is smaller than before, which is useful for future PRs. Many constants being re-created were moved. The address is now pulled from previous calculated and updated addresses.  It also seemed easier to move the switch section to a new function, because it didn't need to share as much as before.

MISC_COLUMNS is a new constexpr which was being used in many places. It may change in the future, so good to keep track of it.

constexpr auto USER_ROLE_IS_ROW_BREAKPOINT_CELL = Qt::UserRole; -- Feels a bit overkill.  It's synonymous with item->column() == 0; But I didn't change it. It could be constexpr int BREAKPOINT_COLUMN = 0;  then column() == BREAKPOINT_COLUMN so it wouldn't need to be set on every item.

2022-10-01 00:17 UTC, Pokechu22 commented
@dolphin-emu-bot rebuild

2022-10-01 11:22 UTC, sepalani requested changes

2022-10-01 11:22 UTC, sepalani commented on Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
> +  }
The `break` statement can be removed because it's unreachable after a `return` statement. Ditto for all the other cases.

2022-10-02 00:50 UTC, Pokechu22 commented
@dolphin-emu-bot rebuild

2022-10-02 00:53 UTC, TryTwo commented
accessors->IsValidAddress(addr)  checks all the conditions we need at once (game is running, memory address exists, and if it exists it has a value)

2022-10-02 01:30 UTC, Pokechu22 commented
@dolphin-emu-bot rebuild

2022-10-02 01:35 UTC, TryTwo commented
Because the table isn't being re-created on update, the item_selected pointer will hold any new values if they change. So there's no need for the refresh check. Don't think there's a case where the item pointer can become invalid while the context menu is open, but if so I could add a check to see if it still exists.

2022-10-06 18:07 UTC, sepalani requested changes
I haven't tested this PR yet but here are some suggestions that might slightly improve performance.

2022-10-07 03:25 UTC, TryTwo commented on Source/Core/DolphinQt/Debugger/MemoryViewWidget.cpp
> +                                         QString{QChar::fromLatin1('.')};
It seems we can't return a QLatin1Char without first converting it to a QString.

2022-10-07 04:29 UTC, Pokechu22 commented
@dolphin-emu-bot rebuild

2022-10-20 13:29 UTC, TryTwo commented
I settled on using m_data_columns, because if Symbols are re-added, it will be a new column on the right-side that will throw the old method off.

I don't know if clone() is faster when creating a table, but I thought it looked a little nicer.  Removed the initial address, because Update() will do that.

2022-10-22 17:33 UTC, sepalani commented
@dolphin-emu-bot rebuild

2022-10-22 18:45 UTC, sepalani reviewed
Tested and working as expected. Beside the lint error the code LGTM too.

2022-10-23 06:00 UTC, sepalani commented
@dolphin-emu-bot rebuild

2022-10-24 01:00 UTC, TryTwo commented
Thanks! I finished fixing it.

2022-11-05 21:59 UTC, merged