MemoryView auto-update while running and color recently changed cells.
dolphin-emu/dolphin pull request #11261
Opened 2022-11-06 22:42 UTC by TryTwo

Add menu items to Memory Widget's mini-menu for auto updates.  I saw the other PR saying the mini-menu is confusing, but we need some place for all these little options.

Uses CPURunAsThread to safely update the viewable memory region while a game is running. Highlights changed cells. Scrolling will reset everything, since the detection is cell-based.

Currently CPURunASThread will trigger UpdateDisasmDialog while a game is running, which can create an infinite loop with the auto-update.  I constrained the update calls in memoryview to fix this, but it would be better if it was never triggered.  I made an attempt to fix it: #11161, but that might not be the right approach. 

I'm also not sure MemoryWidget needs to receive update calls, so I removed those to avoid any issues.

Thoughts?

2022-12-22 05:06 UTC, iwubcode commented
I haven't tested this yet but I was using MemoryView for the first time on master.  It wasn't obvious to me that you had to _pause_ to view values.  That feels _sooo_ cumbersome.  It's difficult to remember what values exist as well.

If this resolves those issues, oh my goodness, this will be such a wonderful thing.  At the moment MemoryView seems almost unusable.  Surprised everyone put up with it all these years..

2022-12-22 06:29 UTC, Minty-Meeo commented
I feel like most people haven't.  Aldelaro5's Dolphin Memory Engine is still much nicer to use for most things.

2022-12-22 16:12 UTC, TryTwo commented
I haven't had any major problems using it as-is. Any work done on memory needs to be done while paused anyway.

This PR will tell you what values change, but not their previous value.

2023-11-20 00:29 UTC, TryTwo commented
Rebuilt using unmerged #12263 as a base for the update logic.

2023-11-21 08:04 UTC, TryTwo commented
Fairly happy with this one.  itemChanged and QSignalBlock were causing many issues while the game was running and updating (probably choking on the CPU being busier).  I replaced itemChanged with a custom signal that only triggers when the user is editing a cell.  It's more reliable and avoids accidental lag.

I think it's almost done. I'll split it into smaller commits and wait for the cheatsearch commits to be looked at.

2023-11-28 04:00 UTC, TryTwo commented
This definitely needs more bug fixes, working on it.

2024-06-24 22:02 UTC, TryTwo commented
With everything being updated to C++20 now, I have this working. Cleaned up the commits. It's ready to be tested.

2025-01-08 00:08 UTC, dreamsyntax commented on Source/Core/DolphinQt/Debugger/MemoryViewWidget.h
> +  void UpdateDisbatcher(UpdateType type = UpdateType::Addresses);
Maybe intentional; or did you mean
Dis**p**atcher rather than Dis**b**atcher?

2025-01-08 00:09 UTC, dreamsyntax commented
> Maybe I could re-look at doing it without the big refactor, which would make it a faster review.
> 
> It worked perfectly for me, but there may have been some other commits that affected it since then.

The refactor IMO isn't a big deal; Keep it since it helps with future PRs

2025-01-08 03:33 UTC, TryTwo commented on Source/Core/DolphinQt/Debugger/MemoryViewWidget.h
> +  void UpdateDisbatcher(UpdateType type = UpdateType::Addresses);
Oh, lol. Thanks, yes.

2025-01-18 19:15 UTC, sepalani requested changes
The code looks almost good to me.

Tested on Windows and it seems to work as expected.

2025-01-18 20:05 UTC, sepalani commented
There is also a typo in the last two commits `MemoryViewWidget::` with two `:` instead of one.

2025-01-20 06:30 UTC, TryTwo commented
Thanks for reviewing.  I got the things pointed out.

2025-01-20 17:41 UTC, sepalani approved these changes
Tested and LGTM.

As a side note, having auto-update enabled can have a performance impact on emulation speed, however, it doesn't harm performance when the widget isn't visible which is nice.

2025-01-20 20:15 UTC, dreamsyntax approved these changes
Since the performance hit goes away when the memory tab is not visible, I don't think the toggle to enable/disable is necessary anymore.

LGTM, merging as is gives a great QoL boost for those using memory widget, and brings it closer to DME parity.

2025-01-28 02:15 UTC, merged