Built-in assembler for debugger interface
dolphin-emu/dolphin pull request #11497
Opened 2023-01-27 15:55 UTC by vyuuui

A feature I've wanted in Dolphin's debugger for a while was some form of integrated assembler. Right now, the only options when trying to do live patches are either using a third party tool to generate a Gecko code, or extracting single machine code words from the output of an assembler and patching each instruction individually in the Code Viewer.

With this change, I'm hoping to introduce two useful features to speed up the old process which will also justify the creation of an entirely handwritten assembler for Gekko being shoved into Dolphin's codebase.

### Assembler Widget
A new docked widget included in the Debugger UI (alongside codeview, regview, etc...). It acts much like an IDE for assembly. Below is a catalogue of its primary feature set
 - Multi-line assembly
 - Syntax highlighting and parse error detection in-editor.
 - Directly applying raw output to RAM
 - Multiple output formats (Raw, AR, Gecko execute, Gecko trampoline)
 - Saving and loading files

[Here's a sample video](https://youtu.be/7A5cqR4LU6k)
Clean themed tab bar icons were designed and illustrated by [Mr. Mendelli](https://github.com/MrMendelli)

### Inline Assembly Patcher
An extra context menu option in the instruction pane within the CodeView widget. It supports assembling a single line, and should make the process of single instruction patches much less annoying. It will initially be filled with the raw machine code of the instruction being patched. The UI will display any errors with the entered assembly, updating on each character typed. It should be relatively self-explanatory.

https://user-images.githubusercontent.com/92327340/215096250-a3d43e70-c146-49f6-bd00-2d918c80ee80.mp4

### Assembler Language
It would also be pertinent to include some documentation for the language itself. Since it's relatively simple, [this markdown document](https://gist.github.com/vyuuui/05307e1c9fc96d288c1a333a00458fba#file-assembler-documentation-md) should be good enough.

2023-01-27 16:14 UTC, Simonx22 commented
@dolphin-emu-bot rebuild

2023-01-28 01:53 UTC, vyuuui commented
Whoops, forgot to run clang-format on this before submitting... I'll split those into three squash-able commits for now.

2023-01-28 02:20 UTC, hzzzr commented
assembly

2023-01-28 02:23 UTC, Pokechu22 commented
@dolphin-emu-bot rebuild

2023-01-28 02:35 UTC, Pokechu22 commented
You've currently got compile errors (missing includes of e.g. `QStringView`), and also formatting errors (possibly caused by a different version of `clang-format`? I'm not entirely sure how to set it up).

Regarding instruction replacement: I think it'd be more useful to pre-populate that with the existing disassembled instruction. The existing instruction patching functionality shows the disassembly of the hex you've typed in, so that probably could be used instead (although I'm not sure if it's always going to be unambiguous enough to produce the same instruction, and there's also a chance that the disassembler produces different results from what the assembler expects).

2023-01-28 04:26 UTC, vyuuui commented
> Regarding instruction replacement: I think it'd be more useful to pre-populate that with the existing disassembled instruction. The existing instruction patching functionality shows the disassembly of the hex you've typed in, so that probably could be used instead (although I'm not sure if it's always going to be unambiguous enough to produce the same instruction, and there's also a chance that the disassembler produces different results from what the assembler expects).

It's as you said -- I would need to modify parts of the disassembler, as the disassembly of some instructions don't match to what the assembler would expect. Changing the disassembler just for that might be outside the purview of this feature, but I'm not against it.

2023-01-28 15:54 UTC, vyuuui commented
Build errors should be dealt with, needed to get it working on windows as well.

2023-01-28 17:31 UTC, vyuuui commented
... As well as fixing the code style. That should be it for now.

2023-01-28 18:00 UTC, Pokechu22 commented
@dolphin-emu-bot rebuild

2023-01-28 20:25 UTC, Pokechu22 commented
There still seem to be some build issues on non-Windows platforms. I think they can be fixed by adding `#include <optional>`, `<vector>`, `<tuple>`, `<utility>` to `GekkoSyntaxHighlight.h`, and (I'm less sure of this) by moving the `#include <filesystem>` before `#include <QFile>` in AssemblyEditor.cpp.

2023-01-29 02:29 UTC, vyuuui commented
Agh, quite annoying. I'll try building from a fresh copy of debian, some transitive include with my installed packages is letting this slip by.

2023-01-29 14:01 UTC, lioncash reviewed
Just did a cursory rundown of everything

2023-01-29 14:01 UTC, lioncash commented on Source/Core/DolphinQt/Debugger/GekkoSyntaxHighlight.h
> +  virtual ~BlockInfo() {}
This can be omitted

2023-01-29 14:01 UTC, lioncash commented on Source/Core/DolphinQt/Debugger/GekkoSyntaxHighlight.h
> +  GekkoSyntaxHighlight(QTextDocument* document) : QSyntaxHighlighter(document), m_mode(0) {}
m_mode can be initialized directly. m_cursor_loc should also have a default initial value.

2023-01-30 14:07 UTC, vyuuui commented on Source/Core/Common/Assembler/AssemblerTables.cpp
> +    auto tmp = list[i];
Got that, as well as a few other places that did a pointless XOR swap.

2023-01-30 14:14 UTC, vyuuui commented on Source/Core/Common/Assembler/AssemblerTables.h
> +extern CaseInsensitiveDict<u32, '_'> sprg_map;
Honestly wasn't aware you could have const globals, since const is supposed to have static linkage. Added to all global 'tables' here.

2023-01-30 14:15 UTC, vyuuui commented on Source/Core/Common/Assembler/CaseInsensitiveDict.h
> +  CaseInsensitiveDict(std::initializer_list<std::pair<std::string_view, V>> const& il)
Hopefully caught every occurrence of it.

2023-01-30 14:25 UTC, vyuuui commented on Source/Core/DolphinQt/Debugger/GekkoSyntaxHighlight.cpp
> +  {
Accidentally left it in from earlier, removed.

2023-01-30 14:26 UTC, Simonx22 commented
@dolphin-emu-bot rebuild

2023-01-30 14:45 UTC, vyuuui commented
Sorry, need to rebase this onto master as well.

2023-01-30 14:53 UTC, Simonx22 commented
@dolphin-emu-bot rebuild

2023-01-31 18:49 UTC, vyuuui commented
Nevermind, anything that was using that set already needed to convert string views to strings anyway, so I'll just roll with set using the default comparator. That should fix the android build failure.

2023-01-31 18:50 UTC, Pokechu22 commented
@dolphin-emu-bot rebuild

2023-02-01 08:37 UTC, hzzzr commented
LGTM!

2023-02-03 23:37 UTC, hzzzr commented
When will this be merged?  I am looking forward to using this interface for my new assembly project 🚀

2023-02-03 23:48 UTC, Pokechu22 commented
It'll probably be a bit because I want to take some time to review it in more detail. If you want to try it out for now, there's a windows build at https://dl.dolphin-emu.org/prs/39/1f/pr-11497-dolphin-latest-x64.7z.

2023-02-26 01:11 UTC, notscimmy commented
Approved! LGTM! Merge! Ship it!

2023-03-09 05:56 UTC, Pokechu22 commented
This seems really neat, but I still haven't had time to review it in detail (and there's a merge conflict now).

As a thought, would it be possible to pre-populate the text field with the disassembled instruction after verifying that the disassembled instruction re-assembles back to the same instruction? I feel like _most_ instructions should be able to round-trip properly (with branch instructions being the most likely exception), and that would make edits a lot easier.

2023-03-09 08:51 UTC, vyuuui commented
There's no rush for me to get this in, I'll deal with that merge conflict.

> As a thought, would it be possible to pre-populate the text field with the disassembled instruction after verifying that the disassembled instruction re-assembles back to the same instruction?

That could work, it would only really break on branch and SIMD instructions. Could try massaging the disassembly of branch, but for SIMD I think there's too many cases of unexpected output (registers prefixed with `p`, formatting operands based on the operation).

2023-11-24 21:44 UTC, TryTwo commented
@vyuuui  Are you still around?

2023-11-26 00:44 UTC, vyuuui commented
Thanks for reminding me, forgot to update this a while ago. Was missing the changes to accessing core, this should build now.

2023-11-26 03:15 UTC, TryTwo commented
@dolphin-emu-bot rebuild

2023-11-26 06:54 UTC, TryTwo commented
Thanks!  Would it be okay to put this in #12312? It might get more testing feedback.

2023-11-26 08:36 UTC, vyuuui commented
Sure, go ahead. This still hasn't been reviewed, so it's likely going to need some changes.

2023-12-04 14:06 UTC, Tilka commented
@vyuuui A very welcome addition!

Could you add license headers to all the new files, please? Just copy-paste from an existing file and replace the year.

2023-12-04 20:23 UTC, sepalani requested changes
Parts of this PR are way beyond my area of expertise. So here is a very basic code review. I haven't tested this PR yet but will very soon. Regardless, very impressive work.

2023-12-04 20:23 UTC, sepalani commented on Source/Core/Common/Assembler/GekkoLexer.h
> +void ConvertStringLiteral(std::string_view literal, std::vector<u8>& out_vec);
The out parameter should be passed as pointer based on [Dolphin coding style](https://github.com/dolphin-emu/dolphin/blob/master/Contributing.md#cpp-code-functions).

2023-12-04 20:23 UTC, sepalani commented on Source/Core/Common/Assembler/GekkoLexer.h
> +  void LookaheadN(std::array<AssemblerToken, N>& tokens_out) const
Ditto regarding the out parameters which should be passed as pointer.

2023-12-04 20:23 UTC, sepalani commented on Source/Core/Common/Assembler/GekkoLexer.cpp
> +#include "Common/Assembler/GekkoLexer.h"
Missing license header.

```suggestion
// Copyright 2023 Dolphin Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

#include "Common/Assembler/GekkoLexer.h"
```

2023-12-04 20:23 UTC, sepalani commented on Source/Core/Common/Assembler/GekkoIRGen.cpp
> +    u32 skip_len = static_cast<u32>(m_eval_stack.back());
```suggestion
    const u32 skip_len = static_cast<u32>(m_eval_stack.back());
```

2023-12-04 20:23 UTC, sepalani commented on Source/Core/Common/Assembler/GekkoIRGen.cpp
> +  std::string name_str(name);
```suggestion
  const std::string name_str(name);
```

2023-12-04 20:23 UTC, sepalani commented on Source/Core/Common/Assembler/GekkoIRGen.cpp
> +  std::string name_str(name);
```suggestion
  const std::string name_str(name);
```

2023-12-04 20:23 UTC, sepalani commented on Source/Core/Common/Assembler/GekkoIRGen.cpp
> +  u32 current_addr = m_active_block->BlockEndAddress();
```suggestion
  const u32 current_addr = m_active_block->BlockEndAddress();
```

2023-12-06 05:22 UTC, vyuuui commented
That should cover everything.

2023-12-06 05:23 UTC, vyuuui commented on Source/Core/DolphinQt/Debugger/AssemblyEditor.cpp
> +    }
this was unsafe-ish regardless (though i think back just spits back 0 if empty?)

2023-12-06 05:24 UTC, vyuuui commented on Source/Core/Common/Assembler/AssemblerShared.cpp
> +
I could have sworn that fmt would just ignore it, as it had been working like this. Regardless, a string should be clearer anyway.

2023-12-06 05:25 UTC, vyuuui commented on Source/Core/DolphinQt/DolphinQt.vcxproj
> +</Project>
thanks, vim...

2023-12-06 08:06 UTC, TryTwo commented
@dolphin-emu-bot rebuild

2023-12-09 23:34 UTC, TryTwo commented
Unless it was fixed in a recent update. When saving, it puts the entire path into the tab name (rather than just the new saved file's name), making it really long. When loading, it correctly puts just the file name.

2023-12-11 10:18 UTC, vyuuui commented
> Unless it was fixed in a recent update. When saving, it puts the entire path into the tab name (rather than just the new saved file's name), making it really long. When loading, it correctly puts just the file name.

Fixed, and reminded me that there is no disambiguation for tabs with matching filenames, so I've changed it to display the full path if multiple files have the same name.

2023-12-11 12:34 UTC, vyuuui commented
Looking more at the current disassembler, it's wildly inaccurate for basically all of the SIMD instructions. It (unnecessarily) includes operations (e.g. `ps_msum pD, pA*pC-pB`), it doesn't show the record bit for SIMD, prefixes registers with `p`, and probably more I'm not immediately seeing.

The choices here are either a ~2k line addition for a brand new disassembler, or patching the existing disassembler to match syntax that this PR expects. Drawbacks to both, and not sure if that's worth doing just to fill the 'Assemble Instruction' dialog box properly, though I'm open to either option if deemed necessary.

2023-12-11 18:32 UTC, TryTwo commented
I wouldn't mind if PS stuff is left for another PR, or just skipped.

Is there a way to convert a gecko code back into PPC? Like codewrite does.
Also how much is AR supported, is there syntax for conditionals (08)?

2023-12-12 02:58 UTC, vyuuui commented
Codewrite uses `vdappc`, which is based on the same disassembler that dolphin uses. It looks like it branched from the original implementation which took the route of more human-friendly output. It all comes from the same source, it just looks like someone else did the work there to make it have assembler-friendly syntax.

2023-12-12 03:05 UTC, vyuuui commented
> Also how much is AR supported, is there syntax for conditionals (08)?

AR only supports direct RAM writes. I'm very open to modifications to the Gecko/AR output, as right now it's very barebones and may behave counterintuitively to what someone inexperienced expects (e.g. referencing absolute addresses with Gecko Exec/Trampoline will *not* do what you want thanks to relocation). I don't think there's a good way to deal with that aside from conjuring up some over-complexified dynamic relocation fixup being emitted alongside the code. My initial idea with the different outputs is more of a convenience factor to format it into a gecko code, and expect the user to be aware they should be writing their asm position independent if needed.

2023-12-12 05:11 UTC, TryTwo commented
Yeah I think being a stand-in for CodeWrite is a good starting place, then later PRs could do more if there's interest.

I don't think I got/understood your thoughts on having two-way conversions for PowerPC Input <-> Gecko Output in the assembly widget.  Would you have to include vdappc for it to work?

2023-12-12 07:06 UTC, vyuuui commented
The point of this was to avoid the inclusion of binary blobs such as vdappc or gnu-as. Moreover, vdappc is built to disassemble binaries, not individual instructions. What would have to be done is either copy the work done in vdappc as a separate disassembler (e.g. into externals, but build it as a library), patch the current disassembler to behave like vdappc, or write a new one. The first option is obviously the most preferable, as it has the least added work.

2023-12-12 07:33 UTC, vyuuui commented
> Yeah I think being a stand-in for CodeWrite is a good starting place, then later PRs could do more if there's interest.
> 
> I don't think I got/understood your thoughts on having two-way conversions for PowerPC Input <-> Gecko Output in the assembly widget. Would you have to include vdappc for it to work?

Oh whoops, I'd misread what you meant, converting Gecko codes back into PPC? I think it just trims off the first two words as well as the trailing `00000000` if present, writes that to a file, then runs *that* through vdappc. Sorry for the misunderstanding.

2023-12-13 00:08 UTC, Tilka commented
I get icon loading errors when using a non-default theme:
```
  Condition: icon.availableSizes().size() > 0
  File: Source/Core/DolphinQt/Resources.cpp
  Line: 53
  Function: LoadNamedIcon
```

2023-12-13 00:57 UTC, Dentomologist reviewed
We should probably have an assembler_ prefix on the icon names to avoid namespace clashing or confusion.

2023-12-13 13:34 UTC, vyuuui commented
> I get icon loading errors when using a non-default theme:
> 

Missed other themes initially, put some placeholders in there that may not fit perfectly with other base themes.

> Other issues (these could be addressed in a future pull request if you prefer):
> 
>     * Unsaved changes are silently lost when closing Dolphin rather than the file tab.

Placed this check the best place I could find, can't attest if that's where it should go er... architecturally?

>     * The editor currently shows dark text on dark background for me (GNOME with dark theme).

This should be dealt with, requires a nasty hack to detect dark mode for custom syntax colors (base color should match system now).

>     * The text size in the editor is rather large. I don't mind that being the default but it's currently not possible to adjust using zoom shortcuts like Ctrl+Mousewheel or Ctrl + +/-/0.

Since the gamelist has a shortcut for that already, its context had to be changed (shouldn't cause issues).

>     * The buttons are probably a bit big. Compare with the buttons in the Breakpoints widget which seem more appropriately sized/padded.

Reduced the size, mostly had them large to get a clear visual on the design.

>     * Maybe the base address field should have some default value instead of being empty?

Just having it fill with 0 for now then.


Other minor changes:
 - Switch output type dropdown to be shorter to fit other themes.
 - Change a few other colors around to account for darker themes.
 - Change unsaved changes dialog to prompt a save, ignore, or cancel

2023-12-13 22:19 UTC, Tilka commented
- Clicking the Inject button should update the debugger state to avoid showing stale data in the other widgets.
- It would be useful to be able to reference symbols from PPCSymbolDB rather than only labels in the current file.

2023-12-13 22:20 UTC, Tilka commented on Source/Core/DolphinQt/Debugger/AssembleInstructionDialog.cpp
> +    m_error_loc_label->setText(tr("<span style=\"color: green; font-weight: bold\">Ok</span>"));
"Ok" -> "OK"

2023-12-15 00:41 UTC, Tilka commented
I've changed a tr() calls to separate HTML formatting from translatable strings. Feel free to squash into your commits if you want.

2023-12-15 04:09 UTC, vyuuui commented
Is this something I should be worried about?

2023-12-15 04:10 UTC, AdmiralCurtiss commented
The OSX builder was updated and seems to be producing inconsistent renders, you can ignore it.

2023-12-16 21:15 UTC, merged