Add test for Updater
dolphin-emu/dolphin pull request #11636
Opened 2023-03-10 06:15 UTC by shuffle2

adds full functional test for the updater (windows for now, but should be easy for someone else to add macos in a future pr)

I think I happened to fix https://bugs.dolphin-emu.org/issues/13103 as well (a carriage return was getting into the url!)

2023-03-10 21:01 UTC, delroth requested changes

2023-03-10 21:01 UTC, delroth commented on Tools/test-updater.py
> +#!/usr/bin/env python3
Could you run `black` on this to get some more standard formatting?

2023-03-10 21:01 UTC, delroth commented on Tools/test-updater.py
> +from Crypto.PublicKey import ECC
Could you have a toplevel comment in this file with the non-standard dependencies? Looks like it's only Cryptodome right now?

2023-03-10 21:07 UTC, delroth commented on Source/Core/WinUpdater/Platform.cpp
> +      auto val_start = equals_index + 1;
Can you make this a separate commit?

2023-03-10 21:12 UTC, delroth commented on Tools/test-updater.py
> +HTTP_SERVER_ADDR = ('localhost', 80)
Dunno, 8042? Bonus points if you make it command line configurable with argparse :-)

2023-03-10 21:14 UTC, delroth commented on Source/Core/WinUpdater/Platform.cpp
> +  if (UI::IsTestMode())
OK, I don't feel super strongly about this but I'm a bit worried this could be fragile still. Your call.

2023-03-10 21:36 UTC, delroth commented on Source/Core/DolphinQt/Updater.cpp
> +  if (info.new_shortrev == "updater-test")
That sounds fine -- any reason to pass it through all the way from the updater lib though? I think I have a weak preference here for making the logic as easy to understand as possible given the implication (bypassing user consent for an update).

2023-03-10 21:41 UTC, delroth commented on Source/Core/DolphinQt/Updater.cpp
> +  if (info.new_shortrev == "updater-test")
Yeah, I'd just have a getenv here directly. As I've said though, weak preference, the main thing I care about is that there shouldn't be any accidental backdoors that our update checking service can trigger.

2023-03-10 21:57 UTC, BhaaLseN commented on Source/Core/UICommon/AutoUpdate.cpp
> +    OnUpdateAvailable(nvi);
You got curlies on the `if`, we need balance in the force.
```suggestion
  else
  {
    OnUpdateAvailable(nvi);
  }
```

2023-03-10 21:57 UTC, BhaaLseN commented on Source/Core/WinUpdater/Platform.cpp
> +         (exit_code == ERROR_SUCCESS || exit_code == ERROR_SUCCESS_REBOOT_REQUIRED);
This feels like it should also be its own commit, since it isn't directly related to the test.

2023-03-10 22:43 UTC, BhaaLseN commented on Source/Core/WinUpdater/Platform.cpp
> +         (exit_code == ERROR_SUCCESS || exit_code == ERROR_SUCCESS_REBOOT_REQUIRED);
Oh, I didn't really pay much attention to its call sites. If thats really the case, you can just ignore this one.

2023-03-13 14:47 UTC, delroth approved these changes

2023-03-13 14:47 UTC, merged