Contributing.md: Make our stance on leaked information explicit
dolphin-emu/dolphin pull request #12267
Opened 2023-11-02 19:10 UTC by JosJuice

We have been operating on this principle for a while. Let's make it explicit so that new contributors know about it.

Feedback on wording and structure is welcome.

2023-11-02 19:42 UTC, BhaaLseN commented
I wonder if "confidental information about the GameCube or Wii" is good enough, or whether people can possibly see this as invitation to go like "oh, but I worked on Triforce lemme copy this over". Not sure how to extend on this though, in a way thats generic yet clear enough to get that point across. Maybe something like "about the GameCube, Wii or its associated hardware/software"?

Otherwise, the rest looks good to me; and just like yourself I was surprised that we didn't have this in writing in here yet.

2023-11-02 19:56 UTC, JosJuice commented
I made the wording a bit broader and explicitly mentioned Triforce.

2023-11-02 20:52 UTC, BhaaLseN approved these changes
I don't have anything else to add at this point; so LGTM to get something out there.

2023-11-02 23:49 UTC, dreamsyntax requested changes

2023-11-02 23:49 UTC, dreamsyntax commented on Contributing.md
> +If you know any confidential information related to the GameCube, Wii or Triforce, either because you signed a non-disclosure agreement or because you looked at leaked materials, we ask that you don'
comma after `Wii`

2023-11-03 00:34 UTC, mbc07 approved these changes

2023-11-03 18:40 UTC, AdmiralCurtiss approved these changes

2023-11-03 19:42 UTC, OatmealDome approved these changes

2023-11-03 21:22 UTC, dreamsyntax approved these changes

2023-11-03 21:37 UTC, merged