Core: Implement automatic symbol demangling
dolphin-emu/dolphin pull request #13216
Opened 2024-12-08 02:01 UTC by CelestialAmber

The plan for this PR is to implement automatic symbol demangling which occurs whenever a symbol's name is updated (either when symbols are loaded from a map/ELF/RSO file, or if a symbol name is manually changed). Additionally, there will be two toggles to allow for the feature to be enabled or disabled: one for controlling whether Dolphin should perform automatic demangling when a name is updated, and another to determine if the code debugger tab should display mangled or demangled names.

- [x] Symbol demangler
- [x] Functionality for demangling symbols upon name update
- [ ] Update Code tab
- [ ] Implement toggles

2025-03-25 16:15 UTC, CelestialAmber commented
![Screenshot 2025-03-25 114135](https://github.com/user-attachments/assets/57e08bea-9975-4a37-9946-9583d1a5a077)

Idk why this happens

2025-04-04 13:03 UTC, sepalani requested changes
This is a pretty big PR so you might want to address each change step by step and test them to make sure they don't break anything.

I'm no parser or demangler expert but here are some of the elements I noticed:
 - There are some [coding style](https://github.com/dolphin-emu/dolphin/blob/master/Contributing.md) issues.
 - Parts of the code can be improved using a more C++ish approach.
 - Some variables can be `const`.
 - Less opaque structures can be used to make the code clearer.
 - These structures might remove, in some instances, the need of using `std::tie`/structured binding.
 - Some SPDX/header concerns.
 - Some legal concerns regarding the inclusion of the test cases, though, IANAL.

2026-01-01 21:21 UTC, CelestialAmber commented on Source/Core/Common/CWDemangler.cpp
> +    if (!(std::istringstream(str.substr(1, 1)) >> count))
When mwcc mangles symbol names, it only keeps the last 9 namespaces in the name. For example, if a function is within 10 namespaces (N1 to N10), the total number of parts in the name would be 10, so mwcc would drop the furthest out part (aka the first namespace, N1), and only keep N2-N10 in the name.

<img width="1629" height="599" alt="image" src="https://github.com/user-attachments/assets/e36dfb4a-3f93-45d3-8107-9a423578baa2" />


As a result, the depth will never be above 9, and you can always assume there will only be 1 digit in the number.

2026-01-17 21:29 UTC, sepalani requested changes
Thank you for addressing many of the aforementioned review comments. I gave it another review. However, I haven't tested this new build yet.

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.h
> +// SPDX-License-Identifier: Apache-2.0 OR MIT
Assuming licences are compatible and based on an [existing file here](https://github.com/dolphin-emu/dolphin/blob/master/Source/Android/jni/GpuDriver.cpp#L1-L6), shouldn't the header be something like this instead:

```suggestion
// Copyright 2026 Dolphin Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

// Based on: https://github.com/encounter/cwdemangle
// Copyright 2024 Luke Street <luke@street.dev>
// SPDX-License-Identifier: Apache-2.0 OR MIT
```

I grabbed the author information from the following file: `main/lib/Cargo.toml`. AFAICT, there is no additional contributors as of date.

I'm no SPDX nor licence/copyright expert so someone with more experience should probably confirm that. I've also seen projects using the deprecated `SPDX-ArtifactOfProjectHomePage` to mention the project which the file is derived from.

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +// SPDX-License-Identifier: Apache-2.0 OR MIT
Ditto regarding the header change.

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.h
> +{
Any reason for the namespace not to encapsulate the above structs?

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.h
> +  }*/
Comments should be removed if unused.

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.h
> +  bool mw_extensions = false;
Should be `//` comments as per [Dolphin's coding style](https://github.com/dolphin-emu/dolphin/blob/master/Contributing.md#general).

```suggestion
struct DemangleOptions
{
  // Replace `(void)` function parameters with `()`
  bool omit_empty_parameters = true;
  // Enable Metrowerks extension types (`__int128`, `__vec2x32float__`, etc.)
  //
  // Disabled by default since they conflict with template argument literals
  // and can't always be demangled correctly.
  bool mw_extensions = false;
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.h
> +#include <tuple>
`<tuple>` doesn't seem used in this header file anymore, so it should be removed.

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +  return true;
I believe this can be simplified using `<algorithm>`
```c++
return std::ranges::none_of(s, [](u8 c) { return c > 127; });
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +};
These structs are leaking into the global namespace. They should be inside an anonymous namespace or the `CWDemangler` namespace instead.

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +#include <sstream>
Is `<sstream>` still used?

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    if (!std::isdigit(str[idx]))
The behaviour of many `cctype` functions is undefined if the argument's value is neither representable as `unsigned char` nor equal to `EOF`.

`str[idx]` is of type (plain) `char`, the signedness being implementation defined, it can be negative _(thus, can lead into a crash in some circumstances, e.g. Windows debug builds)_.

`str[idx]` should be converted into `u8` or better, the `<locale>` alternative can be used instead:
```c++
std::isdigit(str[idx], std::locale::classic())
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +  if (str.length() > 0 && std::isdigit(str[0]))
Ditto regarding `std::isdigit` undefined behaviour.

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +  }
Is the whole `contains_non_digit` logic necessary? Won't `idx` be equal to `.size()` at the end of the while loop? 

BTW, was the previous suggestion not working?

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +}
Is the whole `contains_non_digit` logic necessary? Won't `idx` be equal to `.size()` at the end of the while loop? 

BTW, was the previous suggestion not working?

> Can't the same logic be simplified using a `std::string_view`? Maybe something like this:
> ```c++
> struct ParsedDigits
> {
>     std::size_t value = 0;
>     std::string_view remainder;
> };
> 
> std::optional<ParsedDigits> parse_digits(std::string_view sv)
> {
>     if (sv.empty())
>       return std::nullopt;
> 
>     const char* begin = sv.data();
>     const char* end = begin + sv.size();
>     ParsedDigits parsed_digits;
>     const auto result = std::from_chars(begin, end, parsed_digits.value);
> 
>     if (result.ec != std::errc{})
>         return std::nullopt;
>     if (result.ptr != end)
>         parsed_digits.remainder = std::string_view(result.ptr, end - result.ptr);
>     return parsed_digits;
> }
> ```
> I toyed with this example here: https://godbolt.org/z/G7bh1qMvb

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +  };
Is `tmpl_args.clear()` necessary? AFAICT, `tmpl_args` should already be empty if `start_idx != std::string::npos` is false.

The semi-colon at the end of the `else` block is also unnecessary.

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +  {
The condition can be inverted to reduce the indentation level and return early:
```c++
if (start_idx == std::string::npos)
  return {{str, tmpl_args}}
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    };
This semi-colon at the end of the `switch` statement seems unnecessary.

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    std::size_t end_idx = str.rfind('>');
```suggestion
    const std::size_t end_idx = str.rfind('>');
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    const auto demangle_arg_result = demangle_arg(demangled_func_args.rest.substr(1), options);
Note to self: recursive function.

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +  if (start_idx != std::string::npos)
`start_idx` can be `const` and the condition can be inverted to reduce the indentation level and return early _(just like what was done for `end_idx`)_.

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +  std::string tmpl_args;
`tmpl_args` can be declared and assigned further down, closer to where it's being used.

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    str = str.substr(0, start_idx);
For clarity and to make your intent clearer you might want to assign it to another variable with an appropriate name instead (e.g. `std::string_view template_name` or similar). Alternatively, you can declare `DemangleTemplateArgsResult` here and assigning the result to its `.name` member directly.

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +  const std::string result_name = {name.begin(), name.end()};
Can't the `std::string` be constructed from the `std::string_view` like this: `const std::string result_name{name}`?

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +  int index = 0;
```suggestion
  std::size_t index = 0;
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +  int index = 0;
```suggestion
  std::size_t index = 0;
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +  {
The condition can be inverted to reduce the indentation level and return early:
```c++
if (!str.starts_with('Q'))
  return demangle_name(str, options);
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +      return std::nullopt;
Isn't using `from_chars` for that a bit overkill, rather than checking `str[1]` directly instead?

For instance
```c++
// (might be worth explaining here that the max namespace depth is 9)
const int count = str[1] - '0';
if (count < 0 || count > 9)
  return std::nullopt;
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +  str = str.substr(index);
The following should be equivalent:

```suggestion
  str.remove_prefix(index);
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    std::string_view args = str.substr(start_idx + 1, end_idx - (start_idx + 1));
Unless I'm mistaken, you properly checked the index so you can also use this constructor that takes first/last iterators:

```suggestion
    std::string_view args(&str[start_idx + 1], &str[end_idx]);
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    return {{out_val, "", parsed_val.rest}};
Since you checked that the optional wasn't empty, you can safely access its members using `->`:

```suggestion
    const std::string out_val = fmt::format("-{}", parse_result->digits);
    return {{out_val, "", parse_result->rest}};
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    return {{result, "", demangled_name.rest}};
Ditto regarding optional's `->`:

```suggestion
    result += demangle_name_result->full;
    result += post;
    return {{result, "", demangle_name_result->rest}};
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +      result += post;
Can't it be simplified as follows?

```suggestion
      result += fmt::format("{}{}", num, post);
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    return {{result, "", demangled_qual.rest}};
Ditto regarding optional's `->`:
```suggestion
    result += demangle_qual_result->full;
    result += post;
    return {{result, "", demangle_qual_result->rest}};
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    pre = fmt::format("{}::*{}", demangled_qual.full, pre);
Ditto regarding optional's `->`:
```suggestion
    rest = demangle_qual_result->rest;
    pre = fmt::format("{}::*{}", demangle_qual_result->full, pre);
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    str = str.substr(1);
```suggestion
    str.remove_prefix(1);
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +        str = str.substr(6);
```suggestion
        str.remove_prefix(6);
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +        str = str.substr(5);
```suggestion
        str.remove_prefix(5);
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    return {{res_pre, res_post, demangled_arg.rest}};
Ditto regarding optional's `->`:
```suggestion
    const std::string const_str = const_member ? " const" : "";
    const std::string res_pre = fmt::format("{} ({}{}", demangle_arg_result->arg_pre, pre, post);
    const std::string res_post =
        fmt::format(")({}){}{}", demangled_func_args.args, const_str, demangle_arg_result->arg_post);
    return {{res_pre, res_post, demangle_arg_result->rest}};
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    return {{result, ret_post, demangled_arg.rest}};
Ditto regarding optional's `->`.

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +      break;
Is this isolated `break` intended?

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    str = demangled_arg.rest;
Ditto regarding optional's `->`:
```suggestion
    result += demangle_arg_result->arg_pre;
    result += demangle_arg_result->arg_post;
    str = demangle_arg_result->rest;
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    return fmt::format("operator {}{}", demangled_arg.arg_pre, demangled_arg.arg_post);
Ditto regarding optional's `->`:
```suggestion
    return fmt::format("operator {}{}", demangle_arg_result->arg_pre, demangle_arg_result->arg_post);
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +/// Returns `null` if the input is not a valid mangled name.
Should be using `//` as per Dolphin coding style. I suppose it doesn't return `null` but an empty optional/nullopt.

For instance:
```suggestion
// Try to demangle a symbol name.
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +  std::string qualified;
Unless I'm mistaken, some of these variables can be moved further down, closer to where they're being used.

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +        rest = rest.substr(rest_idx + 2);
```suggestion
        rest.remove_prefix(rest_idx + 2);
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    str = demangled_qual.rest;
Ditto regarding optional's `->`:
```suggestion
    class_name = result->class_name;
    qualified = result->full;
    str = result->rest;
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    str = str.substr(1);
```suggestion
    str.remove_prefix(1);
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    str = func_args.rest;
Ditto regarding optional's `->`:
```suggestion
    if (options.omit_empty_parameters && result->args == "void")
    {
      fn_name = fmt::format("{}()", fn_name);
    }
    else
    {
      fn_name = fmt::format("{}({})", fn_name, result->args);
    }
    str = result->rest;
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    str = str.substr(1);
```suggestion
    str.remove_prefix(1);
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    str = demangled_arg.rest;
Ditto regarding optional's `->`:
```suggestion
    return_type_pre = result->arg_pre;
    return_type_post = result->arg_post;
    str = result->rest;
```

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +/// template argument list or operator name.
Should be `//` comment as per Dolphin coding style.

2026-01-17 21:29 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    const std::string_view rest = result.value().rest;
```suggestion
    const std::string_view rest = result->rest;
```

2026-01-17 21:29 UTC, sepalani commented on Source/UnitTests/UnitTests.vcxproj
> +    <ClCompile Include="Common\CWDemanglerTest.cpp" />
Unless I'm mistaken, you should also edit `Source/UnitTests/Common/CMakeLists.txt` to add this cpp file to the UnitTests on other platforms.

2026-01-17 21:29 UTC, sepalani commented on Source/UnitTests/Common/CWDemanglerTest.cpp
> +// SPDX-License-Identifier: Apache-2.0 OR MIT
Ditto regarding the header change.

2026-01-28 19:24 UTC, sepalani commented
As far as I can tell, the code looks good to me. Tested with the following GC games (ELF symbols):
 - Le Monde de Némo
 - Mario Smash Football
 - Need for Speed Underground 1 and 2

The results are fine except for NFSU1/2 where some symbols aren't properly demangled. I don't know if they were compiled with CW, some symbols are properly demangled while others aren't.

@JosJuice 
Any thought on the following, because I'm not confident about how fine this PR is:
 - regarding the license of cwdemangle from which this PR is based on
 - regarding the unit tests and its symbols origin

Pinging @dreamsyntax and @TryTwo in case you might be interested in testing this PR related to Dolphin debugger and CW symbol demangling.

2026-01-28 19:29 UTC, sepalani approved these changes
Tested, I'm approving the code which seems fine so far.

However, as explained, I have some other concerns, where I don't think I have enough expertise to completely approve this PR.

2026-01-28 19:34 UTC, CelestialAmber commented
Many of the symbols come from Metroid Prime games, so they might need to be replaced. I'm still not sure how to go about that, though. I was thinking either I could find/come up with entirely new but similar symbols, or just replace all the names in the symbols with random ones.

I'd be glad to hear what everyone else thinks, though. Ideally they'd be able to stay, but I understand your concern.

2026-01-29 13:28 UTC, dbalatoni13 commented
> The results are fine except for NFSU1/2 where some symbols aren't properly demangled. I don't know if they were compiled with CW, some symbols are properly demangled while others aren't.
> 
Those games were compiled using ProDG which is GCC 2.95 underneath. This is also true for Most Wanted.

2026-01-31 11:01 UTC, JosJuice commented
> regarding the license of cwdemangle from which this PR is based on

It's available under MIT, so we can use it no problem. However, it seems like it was relicensed to CC0 just a few days ago, which is even more permissive. I would suggest updating the PR to note that the code is licensed under `Apache-2.0 OR MIT OR CC0-1.0`.

Also, regardless of whether you do that, please update Externals/licenses.md.

> regarding the unit tests and its symbols origin

Maybe using those symbols would be okay, but if we're able to come up with symbols on our own instead of taking them from a licensed game, I would prefer that.

2026-03-17 16:48 UTC, CelestialAmber commented
I've been thinking about what to do about replacing the symbols, but I don't have any particularly good ideas that everyone would be okay with. The best one that I came up with is just replacing all the names in the symbols with random nouns/words, but I think some might feel that doesn't remove the copyright issue entirely. On top of that, it would be better to have symbols that are actually coherent, instead of ones with completely random unrelated names. At this point I'm kind of tempted to just remove most of the test cases that would likely have copyright issues, and settle with that.

2026-03-24 13:44 UTC, CelestialAmber commented
I decided to replace all of the symbols from retail games with Dolphin's own symbols, so I assume now there won't be any copyright issues.

2026-04-01 20:23 UTC, vabold commented on Source/Core/Common/CWDemangler.cpp
> +    {'w', "wchar_t"}, {'v', "void"},      {'e', "..."},
```suggestion
    {'w', "wchar_t"}, {'v', "void"},      {'e', "..."},   {'r', "long double"},
```

This is a missing case in the original Rust code.

2026-04-15 16:29 UTC, CelestialAmber commented
@sepalani  Sorry for the ping, but I wanted you to review it again to hopefully get this PR finally merged soon.

2026-04-15 16:56 UTC, sepalani commented
> @sepalani Sorry for the ping, but I wanted you to review it again to hopefully get this PR finally merged soon.

Sorry, I was quite busy this past month. I'll definitively take a look at it this week-end. IIRC, my only remaining concern was the symbols, so if that part was addressed and the code hasn't changed much, it shouldn't take me too long.

2026-04-18 13:24 UTC, sepalani requested changes
You should rebase your PR to latest master, I suspect this might fix the build error and fifoci diff.

The code doesn't seem to have changed much. I tested the PR on Windows and it seems to work as expected.

2026-04-18 13:24 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +  const int digit = (int)(str[1] - '0');
```suggestion
  const int digit = static_cast<int>(str[1] - '0');
```

2026-04-18 13:24 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    std::size_t size = parse_result->digits;
```suggestion
    const std::size_t size = parse_result->digits;
```

2026-04-18 13:24 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +  if (str.length() > 0 && std::isdigit((u8)str[0]))
```suggestion
  if (str.length() > 0 && std::isdigit(static_cast<u8>(str[0])))
```

2026-04-18 13:24 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +  char c = str[0];
```suggestion
  const char c = str[0];
```

2026-04-18 13:24 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +  bool guard = str.starts_with("@GUARD@");
```suggestion
  const bool guard = str.starts_with("@GUARD@");
```

2026-04-18 13:24 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +        std::size_t rest_idx = rest.substr(2).find("__");
```suggestion
        const std::size_t rest_idx = rest.substr(2).find("__");
```

2026-04-18 13:24 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    std::size_t first_idx = fn_name.find('$');
```suggestion
    const std::size_t first_idx = fn_name.find('$');
```

2026-04-18 13:24 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +      std::size_t second_idx = fn_name.substr(first_idx + 1).find('$');
```suggestion
      const std::size_t second_idx = fn_name.substr(first_idx + 1).find('$');
```

2026-04-18 13:24 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +  std::size_t length = s.length();
```suggestion
  const std::size_t length = s.length();
```

2026-04-18 21:42 UTC, iwubcode reviewed
Nice work!  Just some comments around string allocations.

2026-04-18 21:42 UTC, iwubcode commented on Source/Core/Common/CWDemangler.cpp
> +static const std::map<std::string, std::string> operators = {
```suggestion
static const std::map<std::string_view, std::string_view> operators = {
```

2026-04-18 21:42 UTC, iwubcode commented on Source/Core/Common/CWDemangler.cpp
> +static const std::map<char, std::string> types = {
```suggestion
static const std::map<char, std::string_view> types = {
```

2026-04-18 21:42 UTC, iwubcode commented on Source/Core/Common/CWDemangler.cpp
> +  std::string func_name;
```suggestion
  std::string_view func_name;
```

2026-04-18 21:42 UTC, iwubcode commented on Source/Core/Common/CWDemangler.cpp
> +  std::string type;
```suggestion
  std::string_view type;
```

2026-04-18 21:42 UTC, iwubcode commented on Source/Core/Common/CWDemangler.cpp
> +  return {{result, "", str.substr(1)}};
```suggestion
  return {{fmt::format("{}{}{}", result, type, post), "", str.substr(1)}};
```

2026-04-18 21:42 UTC, iwubcode commented on Source/Core/Common/CWDemangler.cpp
> +    auto [class_name, full, rest] = result.value();
```suggestion
    auto [class_name, full, rest] = *result;
```

You already did the check, it's not needed to do it again

2026-04-18 21:42 UTC, iwubcode commented on Source/Core/Common/CWDemangler.cpp
> +  std::string pre = parse_qual_result.pre;
```suggestion
 const std::string& pre = parse_qual_result.pre;
```

2026-04-18 21:42 UTC, iwubcode commented on Source/Core/Common/CWDemangler.cpp
> +  std::string post = parse_qual_result.post;
```suggestion
 const std::string& post = parse_qual_result.post;
```

2026-04-18 21:42 UTC, iwubcode commented on Source/Core/Common/CWDemangler.cpp
> +    const std::string const_str = const_member ? " const" : "";
```suggestion
    const std::string_view const_str = const_member ? " const" : "";
```

2026-04-19 21:19 UTC, CelestialAmber commented on Source/Core/Common/CWDemangler.cpp
> +  std::string pre = parse_qual_result.pre;
It gets modified later, so this doesn't work

2026-04-20 01:32 UTC, vabold commented on Source/Core/Common/CWDemangler.cpp
> +    {'w', "wchar_t"}, {'v', "void"},      {'e', "..."},   {'r', "long double"},
```suggestion
    {'w', "wchar_t"}, {'v', "void"},      {'e', "..."},   {'r', "long double"},
    {'D', "short double"},
```
Sorry to add yet another review comment.

2026-05-01 17:17 UTC, sepalani requested changes
Other than that, this PR seems to still be working as expected.

2026-05-01 17:17 UTC, sepalani commented on Source/Core/DolphinQt/Settings.h
>    // Auto-Update
Missing newline, i.e. before `// Auto-Update`

2026-05-01 17:17 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +std::optional<std::size_t> find_split(std::string_view s, bool special, DemangleOptions options);
Unless there is a good reason not to do so, this function should be moved up and defined here (not forward declared). This function should be made `static` as well since it's not declared in the header nor meant to be used externally.

2026-05-01 17:17 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +  {
Is this new braced block intended or is it missing an `else` statement? If it's intended, what is its purpose?

2026-05-01 17:17 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +    auto idx_temp = find_split(str, special, options);
Can't `idx_temp` be `const`?

2026-05-01 17:17 UTC, sepalani commented on Source/Core/Common/CWDemangler.cpp
> +      rest_temp = rest_temp.substr(1);
Can't it be done with a single `.substr(first_idx + 1)`?

2026-05-17 17:12 UTC, sepalani approved these changes
LGTM. I tested the Windows debug build with several games and their symbols (map/elf files).

2026-05-17 18:21 UTC, CelestialAmber commented
This time, could whoever merges the PR make sure I get included as an author of the commit? Just saying this in advance.

2026-05-17 19:19 UTC, Dentomologist commented
> This time, could whoever merges the PR make sure I get included as an author of the commit? Just saying this in advance.

Are you referring to https://github.com/dolphin-emu/dolphin/commit/57b1234feb01ad5bbe7bdbf2bffd2a14590e560e? That commit is a separate merge commit that has two parents (which you can see listed on the linked page). The first parent is the previous version's merge commit (https://github.com/dolphin-emu/dolphin/commit/0a84d93a8e64d946405b0e17edd1a29ccfac0606) and the other one is your commit (https://github.com/dolphin-emu/dolphin/commit/1c4bfc35d980856033714a84a8425e71576623eb), which has you listed as the author.

2026-07-05 15:38 UTC, merged