WiimoteEmu: Expose IMU pointing accelerometer weight setting.
dolphin-emu/dolphin pull request #9147
Opened 2020-10-12 23:32 UTC by jordan-woyak

Reducing this value can produce a less jittery pointer with reduced drift correction.

A user reported they had better results with 1% vs the default 2%.

I don't think I like the name "Accelerometer Correction".
"Accelerometer Weight" will probably confuse people.
Suggestions?

2020-10-13 01:05 UTC, iwubcode commented
Just based off your comment, I'm inclined to suggest "Accelerometer drift correction" or something to that effect.

And then maybe instead of a value, have a combo box with "high", "medium", "low" with some preset values.  Otherwise I imagine users are going to crank it up to 100%.

2020-10-13 03:39 UTC, Rumi-Larry commented on Source/Core/InputCommon/ControllerEmu/ControlGroup/IMUCursor.cpp
> +              _trans("Influence of accelerometer data on pitch and roll.")},
Consider instead "Accelerometer induced pitch-and-roll bias"

2020-10-24 11:06 UTC, rlnilsen commented
This setting is the ratio of how much trust you put in accelerometer vs gyroscope data (at least in my original code, I don't know if the new quaternion stuff is exactly equivalent). The gyroscope is accurate but drifty, the accelerometer is inaccurate but does not drift. So we mostly trust the gyroscope (98% by default), but use the accelerometer to correct gyroscope drift. So maybe "Accelerometer to gyroscope trust ratio"? I'm bad with names.

> ... I'm inclined to suggest "Accelerometer drift correction" or something to that effect.

Unlike gyroscopes, accelerometers do not have drift.

2020-10-24 12:52 UTC, rlnilsen requested changes
The code ~~is untested by me but~~ seems very straight forward and boiler plate, so once the wording issues are resolved this LGTM.

Edit: Gave it a spin and seems to be working well. The pointer gets pretty shaky already at 5%, so I don't know how useful it is to go above that though. This was with a DS4.

2020-10-24 23:51 UTC, rlnilsen commented
Perhaps just "Drift Correction" would be sufficient? That's really all one needs to draw the user's attention if they are experiencing drift. Then the tooltip can give a deeper explanation.

2021-08-01 20:35 UTC, JMC47 commented
I like the idea of drift correction for the user facing option name.  If that's the only thing blocking this, we should probably change this and merge it.

2022-03-03 00:57 UTC, jordan-woyak commented
My issue with "Drift Correction" is it doesn't convey that accelerometer data is used.
In the future we might also have correction from IR data or whatever.
I'm leaning towards maybe "Accelerometer Coefficient" or "Accelerometer Weight".

2022-07-07 21:07 UTC, AdmiralCurtiss commented
Do you want to put this as an Advanced setting now that we have that?

2022-07-07 21:14 UTC, jordan-woyak commented
> Do you want to put this as an Advanced setting now that we have that?

I'm thinking not. It's already on an "Advanced" tab.

2022-07-07 21:17 UTC, AdmiralCurtiss commented
Well alright then, this seems good otherwise, so...

2022-07-07 21:17 UTC, merged