Jit64: More constant propagation optimizations
dolphin-emu/dolphin pull request #9262
Opened 2020-11-19 22:41 UTC by Sintendo

It is possible to generate more optimal instruction sequences for various instructions if some or all of the input registers are known to hold a specific value.

---
**subfic**
<details><summary>Example</summary>

Before:
```
BE 03 00 00 00       mov         esi,3
83 EE 08             sub         esi,8
0F 93 45 58          setae       byte ptr [rbp+58h]
```
After:
```
C6 45 58 00          mov         byte ptr [rbp+58h],0
```
</details>

---

**srwx**
<details><summary>Example 1</summary>

Before:
```
B9 18 00 00 00       mov         ecx,18h
45 8B C1             mov         r8d,r9d
49 D3 E8             shr         r8,cl
```
After:
```
45 8B C1             mov         r8d,r9d
41 C1 E8 18          shr         r8d,18h
```
</details>
<details><summary>Example 2</summary>

Before:
```
B9 00 00 00 00       mov         ecx,0
45 8B C1             mov         r8d,r9d
49 D3 E8             shr         r8,cl
```
After:
```
45 8B C1             mov         r8d,r9d
```
</details>
<details><summary>Example 3</summary>

Before:
```
B9 F8 FF FF FF       mov         ecx,0FFFFFFF8h
45 8B C1             mov         r8d,r9d
49 D3 E8             shr         r8,cl
```
After:
Nothing, register is set to constant zero.
</details>

---
**slwx**

<details><summary>Example 1</summary>

Before:
```
B9 18 00 00 00       mov         ecx,18h
41 8B F7             mov         esi,r15d
48 D3 E6             shl         rsi,cl
8B F6                mov         esi,esi
```
After:
```
41 8B CF             mov         ecx,r15d
C1 E1 18             shl         ecx,18h
```
</details>
<details><summary>Example 2</summary>

Before:
```
BE 00 00 00 00       mov         esi,0
8B CE                mov         ecx,esi
41 8B F3             mov         esi,r11d
48 D3 E6             shl         rsi,cl
8B F6                mov         esi,esi
```
After:
```
41 8B FB             mov         edi,r11d
```
</details>
<details><summary>Example 3</summary>

Before:
```
BE F8 FF FF FF       mov         esi,0FFFFFFF8h
8B CE                mov         ecx,esi
41 8B F4             mov         esi,r12d
48 D3 E6             shl         rsi,cl
8B F6                mov         esi,esi
```
After:
Nothing, register is set to constant zero.
</details>

---

**srawx**
<details><summary>Example 1</summary>

Before:
```
B9 F0 FF FF FF       mov         ecx,0FFFFFFF0h
8B F7                mov         esi,edi
48 C1 E6 20          shl         rsi,20h
48 D3 FE             sar         rsi,cl
8B C6                mov         eax,esi
48 C1 EE 20          shr         rsi,20h
85 F0                test        eax,esi
0F 95 45 58          setne       byte ptr [rbp+58h]
```
After:
```
8B F7                mov         esi,edi
C1 FE 1F             sar         esi,1Fh
0F 95 45 58          setne       byte ptr [rbp+58h]
```
</details>
<details><summary>Example 2</summary>

Before:
```
B9 00 00 00 00       mov         ecx,0
49 C1 E5 20          shl         r13,20h
49 D3 FD             sar         r13,cl
41 8B C5             mov         eax,r13d
49 C1 ED 20          shr         r13,20h
44 85 E8             test        eax,r13d
0F 95 45 58          setne       byte ptr [rbp+58h]
```
After:
```
C6 45 58 00          mov         byte ptr [rbp+58h],0
```
</details>
<details><summary>Example 3</summary>

Before:
```
B9 02 00 00 00       mov         ecx,2
48 C1 E7 20          shl         rdi,20h
48 D3 FF             sar         rdi,cl
48 C1 EF 20          shr         rdi,20h
```
After:
```
C1 FF 02             sar         edi,2
```
</details>
<details><summary>Example 4</summary>

Before:
```
B9 02 00 00 00       mov         ecx,2
49 C1 E5 20          shl         r13,20h
49 D3 FD             sar         r13,cl
41 8B C5             mov         eax,r13d
49 C1 ED 20          shr         r13,20h
44 85 E8             test        eax,r13d
0F 95 45 58          setne       byte ptr [rbp+58h]
```

After:
```
41 8B C5             mov         eax,r13d
41 C1 FD 02          sar         r13d,2
C1 E0 1E             shl         eax,1Eh
44 85 E8             test        eax,r13d
0F 95 45 58          setne       byte ptr [rbp+58h]
```
</details>
<details><summary>Example 5</summary>

Before:
```
B8 00 00 00 00       mov         eax,0
8B F0                mov         esi,eax
C1 E8 1F             shr         eax,1Fh
23 C6                and         eax,esi
D1 FE                sar         esi,1
88 45 58             mov         byte ptr [rbp+58h],al
```
After:
```
C6 45 58 00          mov         byte ptr [rbp+58h],0
```
</details>

---

**rlwnmx**
<details><summary>Example</summary>

Before:
```
B9 02 00 00 00       mov         ecx,2
41 8B F5             mov         esi,r13d
D3 C6                rol         esi,cl
83 E6 01             and         esi,1
```
After:
```
41 8B F5             mov         esi,r13d
C1 C6 02             rol         esi,2
83 E6 01             and         esi,1
```
</details>

2020-12-13 12:40 UTC, Sintendo commented
Added two more optimizations; for slwx and srawx. Similar optimizations are possible for srwx and rlwnmx, but didn't occur during  my tests.

---

**slwx**
<details><summary>Example</summary>

Before:
```
41 BF 00 00 00 00    mov         r15d,0
8B CF                mov         ecx,edi
49 D3 E7             shl         r15,cl
45 8B FF             mov         r15d,r15d
```

After:
Nothing, register is set to constant zero.
</details>

---

**srawx**
<details><summary>Example 1</summary>

Before:
```
41 B9 00 00 00 00    mov         r9d,0
41 8B CF             mov         ecx,r15d
49 C1 E1 20          shl         r9,20h
49 D3 F9             sar         r9,cl
49 C1 E9 20          shr         r9,20h
```

After:
Nothing, register is set to constant zero.
</details>

<details><summary>Example 2</summary>

Before:
```
41 B8 00 00 00 00    mov         r8d,0
41 8B CF             mov         ecx,r15d
49 C1 E0 20          shl         r8,20h
49 D3 F8             sar         r8,cl
41 8B C0             mov         eax,r8d
49 C1 E8 20          shr         r8,20h
44 85 C0             test        eax,r8d
0F 95 45 58          setne       byte ptr [rbp+58h]
```

After:
```
C6 45 58 00          mov         byte ptr [rbp+58h],0
```

</details>

2020-12-20 22:10 UTC, MerryMage requested changes

2020-12-20 22:10 UTC, MerryMage commented on Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
> +      FinalizeCarry(amount != 0 && i < 0 && (i << (32 - amount)));
`(u32(i) << (32 - amount))`

Signed bitwise left shift invokes UB when shifting a negative value.

2020-12-20 22:11 UTC, MerryMage commented on Source/Core/Core/PowerPC/Jit64/Jit_Integer.cpp
> +    FinalizeCarry(amount != 0 && imm < 0 && (imm << (32 - amount)));
ditto

2020-12-21 10:14 UTC, Sintendo commented
Well spotted! The logic for these specific optimizations was actually taken from JitArm64, which has the same problem. I raised a separate PR (#9346) to fix it there as well.

2020-12-25 16:53 UTC, JosJuice approved these changes
LGTM. If you want to get rid of the FifoCI diff, you can do so by rebasing on a newer version of master, but this shouldn't affect the mergeability of your PR.

2020-12-28 01:35 UTC, MerryMage approved these changes

2020-12-28 03:21 UTC, lioncash approved these changes

2020-12-28 03:21 UTC, merged