NetBSD support proposal.
dolphin-emu/dolphin pull request #9309
Opened 2020-12-04 16:10 UTC by devnexen

2020-12-05 21:48 UTC, Rumi-Larry commented
If someone with a pc running NetBSD can test if it builds and runs, then I don't see great harm in adding this. Particularly considering there's Haiku support.

2020-12-05 23:01 UTC, leoetlino requested changes

2020-12-05 23:01 UTC, leoetlino commented on Source/Core/Common/Thread.cpp
> +#ifndef __NetBSD__
Please make two ifndef blocks. This looks horribly error prone. The difference in indentation looked like a style issue at first, until I realised the cpuset_set was guarded by an if statement...

2020-12-05 23:01 UTC, leoetlino commented on Source/Core/Common/StringUtil.cpp
> +          iconv(conv_desc, (const char**)&src_buffer, &src_bytes, &dst_buffer, &dst_bytes);
```suggestion
          iconv(conv_desc, reinterpret_cast<const char**>(&src_buffer), &src_bytes, &dst_buffer, &dst_bytes);
```
(you might need to re-run clang-format after applying this suggestion)

2020-12-11 01:20 UTC, leoetlino commented
@devnexen This fails to build on most builders. You may need a const_cast to fix the issue.

2020-12-11 09:30 UTC, leoetlino requested changes

2020-12-11 09:30 UTC, leoetlino commented on Source/Core/Common/StringUtil.cpp
> +          iconv(conv_desc, const_cast<char**>(reinterpret_cast<char**>(&src_buffer)), &src_bytes, &dst_buffer,
```suggestion
          iconv(conv_desc, const_cast<char**>(reinterpret_cast<const char**>(&src_buffer)), &src_bytes, &dst_buffer,
```

2020-12-15 01:39 UTC, leoetlino approved these changes

2020-12-15 01:41 UTC, merged