GameSettings: Add patch for Monster High: Ghoul Spirit (SAOE78)
dolphin-emu/dolphin pull request #9316
Opened 2020-12-10 02:47 UTC by smurf3tte

The first call to GXCopyDisp() corrupts game data, but on real hardware it isn't observed thanks to the data cache. Skipping the call works too, preventing a crash on boot.

This patch only affects the NTSC-U release (SAOE78) published by THQ. There is a PAL release (SAOP78) of this game, though I suspect it may not be impacted by this bug on account of the default XFB size being larger. Both the NTSC-U and PAL versions were also republished under different game IDs (SAOEVZ/SAOXVZ) by the publisher Little Orbit. One or both of these may also be in need of patching.

2020-12-11 00:52 UTC, leoetlino commented
Marking this as "do not merge" until #9317 is merged.

2020-12-11 09:41 UTC, leoetlino requested changes

2020-12-11 09:41 UTC, leoetlino commented on Data/Sys/GameSettings/SAOE78.ini
> +0x803A5F20:dword:0x60000000
Please enable this by default, with

```ini
[OnFrame_Enabled]
$Fix crash on boot
```

2020-12-11 12:46 UTC, smurf3tte commented on Data/Sys/GameSettings/SAOE78.ini
> +0x803A5F20:dword:0x60000000
Done!

2020-12-11 20:29 UTC, smurf3tte commented
With help from @JMC47 I was able to add support for the version of the game published by Little Orbit (SAOEVZ). They also confirmed that the PAL release does not need this fix. Thanks JMC47!

2020-12-11 20:29 UTC, JMC47 commented
PAL doesn't need a patch.  Tested the patch for the v1.01 version of the game.

2020-12-12 00:55 UTC, leoetlino approved these changes

2020-12-12 12:59 UTC, merged

2021-01-08 18:00 UTC, ytrezq commented
@smurf3tte would it be possible to produce a patch for an Icache access when going in game menus, for this game I own https://bugs.dolphin-emu.org/issues/8037?