GameSettings: Enable compatibility patches by default
dolphin-emu/dolphin pull request #9317
Opened 2020-12-10 15:04 UTC by JosJuice

This pull request makes it possible for users to disable patches that are enabled by default, and enables patches for game-breaking problems by default.

My criterion for which patches to select was that the patch has to make the game's behavior closer to how the game acts on console. So workarounds for Dolphin not emulating caches accurately are enabled by default, but not things like Twilight Princess's minimap speedhack or patches for disabling memory card checks in Pokémon games.

This is a convenience which I think will be appreciated by people who want to play ~[Resident Evil 2 & 3](https://github.com/dolphin-emu/dolphin/pull/9308)~ Casper's Scare School: Spooky Sports Day.

2020-12-10 16:06 UTC, smurf3tte approved these changes
Thanks, I'm eager to start using this! 😄

2020-12-10 17:41 UTC, JMC47 commented
I don't think it's fair to completely rule out some quality of life patches.  I know it's a huge departure from your current criteria of only allowing patches that make games behave *more* like console, and there's a slippery slope argument, but if you look at it from a usability perspective, there's no reason not to have the save patches on for Pokemon unless they malfunction.  How many android users are going to know it's there?

Either way, for the current use?  100% approve.

2020-12-10 18:34 UTC, JosJuice commented
I'm not 100% opposed to extending the criteria, but if we're going to do that, I would like someone to open a separate PR for it so that it doesn't block the merge of this.

> How many android users are going to know it's there?

I do plan on adding cheats/patches to the Android GUI at some point :)

2020-12-11 00:49 UTC, leoetlino requested changes

2020-12-11 00:49 UTC, leoetlino commented on Source/Core/Core/ActionReplay.cpp
> +  local_ini->SetLines("ActionReplay_Disabled", enabled_lines);
```suggestion
  local_ini->SetLines("ActionReplay_Disabled", disabled_lines);
```

2020-12-11 00:49 UTC, leoetlino commented on Source/Core/Core/GeckoCodeConfig.cpp
> +  inifile.SetLines("Gecko_Disabled", enabled_lines);
```suggestion
  inifile.SetLines("Gecko_Disabled", disabled_lines);
```

2020-12-11 00:49 UTC, leoetlino commented on Source/Core/Core/ActionReplay.cpp
> +      disabled_lines.push_back("$" + code.name);
```suggestion
      disabled_lines.emplace_back("$" + code.name);
```
nitpick, but consistency :P

2020-12-11 00:49 UTC, leoetlino commented on Source/Core/Core/CheatCodes.h
> +  ini.GetLines(section + "_Enabled", &lines, false);
Could this + the loop be deduplicated?

2020-12-11 00:49 UTC, leoetlino commented on Source/Core/Core/GeckoCodeConfig.cpp
> +      disabled_lines.push_back("$" + geckoCode.name);
```suggestion
      disabled_lines.emplace_back('$' + geckoCode.name);
```

2020-12-11 00:49 UTC, leoetlino commented on Source/Core/Core/GeckoCodeConfig.cpp
> +      enabled_lines.push_back('$' + geckoCode.name);
```suggestion
      enabled_lines.emplace_back('$' + geckoCode.name);
```

2020-12-11 00:49 UTC, leoetlino commented on Source/Core/DolphinQt/Config/PatchesWidget.cpp
> +      lines_disabled.push_back("$" + patch.name);
emplace_back if possible?

2020-12-11 09:39 UTC, leoetlino approved these changes

2020-12-11 09:40 UTC, merged