Update CMakeLists.txt
dolphin-emu/dolphin pull request #9353
Opened 2020-12-23 07:32 UTC by MaddTheSane

CMake's CMAKE_SYSTEM_PROCESSOR call returns "arm64" on Apple Silicon.

2020-12-23 10:32 UTC, JosJuice commented
@dolphin-emu-bot rebuild

2020-12-24 21:29 UTC, leoetlino requested changes
The changes look fine, but please use a more descriptive commit message. "Update CMakeLists.txt" doesn't tell *anything* about what changes were actually made and why the file was changed. Those are things that should be part of a good commit message.

2020-12-24 21:36 UTC, MaddTheSane commented
A more descriptive commit message is now used.

2020-12-24 21:40 UTC, leoetlino approved these changes

2020-12-24 21:50 UTC, merged