PCAP: Add raw SSL packets logging support
dolphin-emu/dolphin pull request #9499
Opened 2021-02-11 13:34 UTC by sepalani

This PR allows the NetworkLogger to dump raw SSL packets in PCAP format when dumping decrypted SSL packets is disabled.

That way, most network related features would be supported by the logger except for WiiConnect24, DNS and ICMP packets.

Ready to be reviewed & merged.

Depends on https://github.com/dolphin-emu/dolphin/pull/9408.

2021-02-11 20:39 UTC, leoetlino commented
Now that #9408 has been merged, this PR needs a rebase.

2021-02-13 19:30 UTC, sepalani commented
@leoetlino 
Done.

2021-02-14 15:42 UTC, leoetlino requested changes

2021-02-14 15:42 UTC, leoetlino commented on Source/Core/Core/IOS/Network/SSL.cpp
> +  // Log raw SSL packets if we don't dump unencrypted SSL write
```suggestion
  // Log raw SSL packets if we don't dump unencrypted SSL writes
```

2021-02-14 15:42 UTC, leoetlino commented on Source/Core/Core/IOS/Network/SSL.cpp
> +  // Log raw SSL packets if we don't dump unencrypted SSL read
```suggestion
  // Log raw SSL packets if we don't dump unencrypted SSL reads
```

2021-02-14 16:37 UTC, sepalani commented
@leoetlino 
Done.

2021-02-14 17:39 UTC, leoetlino approved these changes

2021-02-14 17:39 UTC, merged