BreakpoinWidget: Allow breakpoints to be toggle between enable/disable.
dolphin-emu/dolphin pull request #9542
Opened 2021-02-28 13:00 UTC by InusualZ

This PR add a way to disable/enable breakpoints at runtime, by adding a context menu that let you toggle between the two state.
Also, added a `Go to` action, that let you go to breakpoint address, this action is only added when the breakpoint is a instruction breakpoint.

![Context Menu](https://user-images.githubusercontent.com/2200611/109419214-4306c480-79c4-11eb-9d55-a2621d453228.png)

I removed the `itemClicked` listener since it was replaced with the context menu `Go to` action.

2021-02-28 14:22 UTC, sepalani commented
@dolphin-emu-bot rebuild

2021-02-28 15:04 UTC, sepalani requested changes

2021-02-28 16:44 UTC, InusualZ commented on Source/Core/Core/PowerPC/BreakPoints.cpp
>      std::stringstream ss;
Nice catch!

2021-02-28 16:45 UTC, InusualZ commented on Source/Core/Core/PowerPC/BreakPoints.cpp
> +    ss << std::hex << mc.start_address << " " << mc.end_address << " " << (mc.is_enabled ? "n" : "")
First time that have amended a commit other than the previous one. What a rush! xD

2021-02-28 16:45 UTC, InusualZ commented on Source/Core/Core/PowerPC/BreakPoints.cpp
> +    ss << std::hex << mc.start_address << " "
Done

2021-02-28 17:12 UTC, sepalani commented
@dolphin-emu-bot rebuild

2021-03-01 16:32 UTC, sepalani reviewed
Do you mind adding `ss.imbue` in `BreakPoints::GetStrings` and `BreakPoints::AddFromStrings` as well? Otherwise, LGTM.

2021-03-01 17:07 UTC, lioncash commented on Source/Core/Core/PowerPC/BreakPoints.cpp
> +  for (auto& bp : m_breakpoints)
std::find_if can be used here. Ditto for the memchecks equivalent function

2021-03-01 17:07 UTC, lioncash commented on Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
> +    menu->addAction(tr(bp_iter->is_enabled ? "Disable" : "Enable"), [this, &bp_address]() {
```suggestion
    menu->addAction(bp_iter->is_enabled ? tr("Disable") : tr("Enable"), [this, &bp_address] {
```

2021-03-01 17:07 UTC, lioncash commented on Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
> +    menu->addAction(tr(mb_iter->is_enabled ? "Disable" : "Enable"), [this, &bp_address]() {
```suggestion
    menu->addAction(mb_iter->is_enabled ? tr("Disable") : tr("Enable"), [this, &bp_address] {
```

2021-03-01 17:07 UTC, lioncash commented on Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
> +    const auto& mb_iter =
```suggestion
    const auto mb_iter =
```

2021-03-01 17:07 UTC, lioncash commented on Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
> +  const auto& bp_iter =
```suggestion
  const auto bp_iter =
```

2021-03-03 05:21 UTC, sepalani commented
@dolphin-emu-bot rebuild

2021-03-03 17:58 UTC, sepalani approved these changes
LGTM

2021-03-03 18:31 UTC, JMC47 commented
Tested and appears to work.

2021-03-03 19:00 UTC, JMC47 commented
I don't know how strict we are with things, but there's a typo in the commit - Allow to disable/enable from the Breakpoin**t**Widget

2021-03-03 19:57 UTC, JMC47 commented
@dolphin-emu-bot rebuild

2021-03-04 11:33 UTC, leoetlino approved these changes

2021-03-04 11:34 UTC, merged

2021-12-26 02:44 UTC, trevor403 commented
Fixes comma separated hex values caused by locale
e.g. 
https://github.com/dolphin-emu/dolphin/pull/9456#pullrequestreview-573535894