BreakpointWidget: Fix delete deleting both MBP and BP at address
dolphin-emu/dolphin pull request #9564
Opened 2021-03-04 17:48 UTC by sepalani

This PR fixes the delete action which deletes everything matching the address of the selected item (i.e. both memory and regular breakpoints).

Ready to be reviewed & merged.

2021-03-04 23:56 UTC, leoetlino requested changes

2021-03-04 23:56 UTC, leoetlino commented on Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
> +    Settings::Instance().blockSignals(true);
I realise this was already written like this, but using a QSignalBlocker would be cleaner here. Idea for a follow-up PR :)

2021-03-04 23:56 UTC, leoetlino commented on Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
> +  auto is_memory_breakpoint = selected_item->data(IS_MEMCHECK_ROLE).toBool();
Why is this randomly not const?
```suggestion
  const auto is_memory_breakpoint = selected_item->data(IS_MEMCHECK_ROLE).toBool();
```

2021-03-04 23:56 UTC, leoetlino commented on Source/Core/DolphinQt/Debugger/BreakpointWidget.cpp
> +    menu->addAction(tr("Go to"), [this, bp_address]() { emit SelectedBreakpoint(bp_address); });
```suggestion
    menu->addAction(tr("Go to"), [this, bp_address] { emit SelectedBreakpoint(bp_address); });
```

2021-03-05 09:19 UTC, sepalani commented
@leoetlino 
Done.

2021-03-05 09:28 UTC, leoetlino approved these changes

2021-03-05 09:28 UTC, merged