Fix various build warnings
dolphin-emu/dolphin pull request #9567
Opened 2021-03-05 19:52 UTC by Dentomologist

Fix a number of build warnings on various platforms.

- Unused variables in Arm64Gen, FreeLookCamera and GraphicsWidget
- Variable shadowing in SDIOSlot0Device and NetworkCaptureLogger
- Unused variable warnings when not using one element of a structured binding pair in WiimoteDevice, ControllerInterface, HighResTexture, and Movie
- Missing maybe_unused attribute for unused but documenting constants in WiimoteDevice
- Missing override specifiers in Touchscreen subclasses and FreeLookCamera
- Spurious gcc warning about discarding return values with warn_unused_result attribute
- Signed/unsigned comparison in InputConfig
- Move Arm64Gen namespace variable into only consuming function (and make constexpr).

2021-03-05 20:25 UTC, Dentomologist commented
Ubuntu is still reporting an unused variable error for the structured bindings.  Looking into it again, it looks like the error might be a gcc bug in versions prior to 8.0.  If that's the case the maybe_unused attributes I added in those locations wouldn't be doing anything and I can revert them.

2021-03-05 20:43 UTC, Dentomologist commented
Other remaining warnings: 

- FreeLookCamera.cpp:315:75: warning: 'old_type' may be used uninitialized in this function [-Wmaybe-uninitialized]

old_type is initialized by m_current_type which is an optional. I don't know yet whether it's possible for that optional to be nullopt, but apparently the compiler thinks so.

- clang: warning: argument unused during compilation: '-fno-objc-exceptions' [-Wunused-command-line-argument]

There's a todo comment where that flag is set noting that it should only be set when compiling with objective c, but that conditional isn't implemented yet.

- /Users/osxguest/buildslave/pr-osx-x64/build/Source/Core/MacUpdater/Main.storyboard:global: warning: This file is set to build for a version older than the deployment target. Functionality may be limited. [9]
- Source/Core/DolphinQt/dolphin-emu_autogen/mocs_compilation.cpp:75:10: warning: non-portable path to file '"PUA4RWX4XS/moc_FreelookWidget.cpp"'; specified path differs in case from file name on disk [-Wnonportable-include-path]

Also the same error for "PUA4RWX4XS/moc_FreelookWindow.cpp" and "Y64OOCBRBB/moc_FreelookGeneral.cpp"

- ../Source/Core/VideoCommon/LightingShaderGen.h:40:23: warning: no previous extern declaration for non-static variable 's_lighting_struct' [-Wmissing-variable-declarations]

That variable is declared constexpr inline which some research seems to indicate should handle the problem, but apparently not.

- Not strictly a warning, but CMake on android complains about not having "Findfmt.cmake".

2021-03-07 11:10 UTC, leoetlino requested changes

2021-03-07 11:10 UTC, leoetlino commented on Source/Core/Core/IOS/USB/Bluetooth/WiimoteDevice.cpp
> +  for ([[maybe_unused]] auto& [cid, channel] : m_channels)
This is actually considered a GCC bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81767

I think this commit should be dropped as it is fixed in newer GCC versions and it hurts readability.

2021-03-07 18:23 UTC, Dentomologist commented
I've dropped the commit adding [[maybe_unused]] to structured bindings and rebased on master.

2021-03-16 08:32 UTC, leoetlino approved these changes

2021-03-16 08:33 UTC, merged