Fix loading save states with bluetooth passthrough
dolphin-emu/dolphin pull request #9583
Opened 2021-03-14 00:47 UTC by michaelszubartowicz

When a save state is loaded, the IOS device serving bluetooth is cast as BluetoothEmuDevice. If, however, a real Wiimote with BT passthrough is used, this caused the game to crash. Now the proper device class is used.

2021-03-14 00:58 UTC, iwubcode commented on Source/Core/Core/HW/Wiimote.cpp
> +    const auto bluetooth = std::static_pointer_cast<IOS::HLE::BluetoothRealDevice>(
This branch seems unnecessary in its current state...it's accessing the bluetooth and doing nothing with it.

Suggest fixing it (not sure what the correct solution would be) or just removing it if there's nothing to do:

```
if (s_wiimote_sources[index] == WiimoteSource::Emulated)
{
    const auto bluetooth = std::static_pointer_cast<IOS::HLE::BluetoothEmuDevice>(
        ios->GetDeviceByName("/dev/usb/oh1/57e/305"));
    if (!bluetooth)
      return;
bluetooth->AccessWiimoteByIndex(index)->SetSource(GetHIDWiimoteSource(index));
  }
```

2021-03-14 01:11 UTC, michaelszubartowicz commented
Thanks for the quick reply. I fixed it.

2021-03-14 10:19 UTC, leoetlino requested changes

2021-03-14 10:19 UTC, leoetlino commented on Source/Core/Core/HW/Wiimote.cpp
> +  if (s_wiimote_sources[index] == WiimoteSource::Emulated)
```suggestion
  if (s_wiimote_sources[index] != WiimoteSource::Emulated)
    return;
```

2021-03-16 08:50 UTC, leoetlino approved these changes
(I took the liberty of rebasing your PR and squashing the commits)

2021-03-16 09:12 UTC, merged