VideoCommon: Return default bounding box values instead of 0
dolphin-emu/dolphin pull request #9773
Opened 2021-05-31 20:32 UTC by Techjar

The SDK seems to write 1023 0 1023 0 to the bounding box registers before every draw, which presumably is used as a mechanism to detect whether GX has written valid values to the registers. By returning these values instead of all 0, we may be able to stop games crashing due to out of bounds memory access when bounding emulation is disabled or unsupported.

2021-05-31 21:19 UTC, JMC47 commented
This makes it so we can run Bounding Box titles without them crashing if Bounding Box is disabled, instead just breaking Visual Effects.  It's actually really useful for examining what they do.

2021-05-31 21:20 UTC, JMC47 approved these changes

2021-05-31 21:25 UTC, phire requested changes
If these "default values" have been written by the sdk before this draw call, then we would have received them in SetBoundingBox.

Rather than hardcoded these "default values" if the desired result is to preserve what was written, then we should modify how BBdisabled works so it accepts writes and just never fetches new results from the host gpu.

2021-05-31 22:10 UTC, phire approved these changes

2021-05-31 22:10 UTC, phire commented on Source/Core/VideoCommon/RenderBase.h
> +  // unsupported, this way games shouldn't crash due to garbage values.
Might be wise to expand upon this comment for the benefit of future developers.

Something like this?

```suggestion
  // Nintendo's SDK seems to write "default" nonsensical bounding box values before every
  // draw (1023 0 1023 0 are the only values encountered so far), which presumably it is
  // using to detect whether GX has updated the registers with real values.
  //
  // We can store these values when Bounding Box emulation is disabled and return them
  // on read, which the game will interpret as "no pixels have been drawn" 
  // 
  // This produces much better results than just returning garbage, which can cause games
  // like SpiderMan 2 to crash.  
```

2021-06-01 00:23 UTC, JMC47 commented on Source/Core/VideoCommon/RenderBase.h
> +  // Nintendo's SDK seems to write "default" bounding box values before every draw (1023 0 1023 0
Missing ) at the end of the first line?

2021-06-01 00:27 UTC, merged