DSP: Fix cycles overhead
dolphin-emu/dolphin pull request #9774
Opened 2021-06-02 17:44 UTC by sepalani

This PR fixes https://dolp.in/i12498. `ForceExceptionCheck` was increasing the current instruction's cycles too much making it way too slow.

I created this hardware test to measure the access timings of some instructions/registers used during Syobon Action boot :  
[wii-cycles-timing.zip](https://github.com/dolphin-emu/dolphin/files/6586410/wii-cycles-timing.zip)

<details><summary>HWTEST results on Wii</summary>
<p>

| BL/BLR   | Attempt 1       | Attempt 2       | Attempt 3       |
|----------|-----------------|-----------------|-----------------|
| BL/BLR   |       1/1       |       1/1       |       1/1       |

| SPRG     | Attempt 1       | Attempt 2       | Attempt 3       |
|----------|-----------------|-----------------|-----------------|
| SPRG0    |       3/3       |       3/3       |       3/3       |
| SPRG1    |       3/41      |       3/12      |       3/12      |
| SPRG2    |       3/3       |       3/3       |       3/3       |
| SPRG3    |       3/3       |       3/3       |       3/3       |

| GQR      | Attempt 1       | Attempt 2       | Attempt 3       |
|----------|-----------------|-----------------|-----------------|
| GQR0     |       5/3       |       5/3       |       5/3       |
| GQR1     |      44/3       |       5/3       |       5/3       |
| GQR2     |       5/43      |       5/3       |       5/3       |
| GQR3     |       5/3       |       5/3       |       5/3       |
| GQR4     |       5/3       |       5/3       |       5/3       |
| GQR5     |      43/3       |       5/3       |       5/3       |
| GQR6     |       5/43      |       5/3       |       5/3       |
| GQR7     |       5/3       |       5/3       |       5/3       |

| DSP REG  | Attempt 1       | Attempt 2       | Attempt 3       |
|----------|-----------------|-----------------|-----------------|
| 5        |      76/57      |      35/1       |      34/1       |
| 24       |      35/1       |      34/1       |      34/1       |
| 25       |      35/1       |      34/1       |      34/1       |
| 27       |      35/1       |      34/1       |      34/1       |

| AI REG   | Attempt 1       | Attempt 2       | Attempt 3       |
|----------|-----------------|-----------------|-----------------|
| 0        |     116/1       |     116/1       |     116/1       |
| 1        |     125/1       |     116/1       |     116/1       |
| 2        |     119/1       |     116/1       |     125/1       |
| 3        |     116/1       |     116/1       |     116/1       |

| PI REG   | Attempt 1       | Attempt 2       | Attempt 3       |
|----------|-----------------|-----------------|-----------------|
| 0        |      46/1       |      47/1       |      47/1       |
| 1        |      45/1       |      47/1       |      47/1       |

</p>
</details>

<details><summary>HWTEST results on Dolphin (custom build)</summary>
<p>

| BL/BLR   | Attempt 1       | Attempt 2       | Attempt 3       |
|----------|-----------------|-----------------|-----------------|
| BL/BLR   |       2/2       |       2/2       |       2/2       |

| SPRG     | Attempt 1       | Attempt 2       | Attempt 3       |
|----------|-----------------|-----------------|-----------------|
| SPRG0    |       3/4       |       3/4       |       3/4       |
| SPRG1    |       3/4       |       3/4       |       3/4       |
| SPRG2    |       3/4       |       3/4       |       3/4       |
| SPRG3    |       3/4       |       3/4       |       3/4       |

| GQR      | Attempt 1       | Attempt 2       | Attempt 3       |
|----------|-----------------|-----------------|-----------------|
| GQR0     |       3/4       |       3/4       |       3/4       |
| GQR1     |       3/4       |       3/4       |       3/4       |
| GQR2     |       3/4       |       3/4       |       3/4       |
| GQR3     |       3/4       |       3/4       |       3/4       |
| GQR4     |       3/4       |       3/4       |       3/4       |
| GQR5     |       3/4       |       3/4       |       3/4       |
| GQR6     |       3/4       |       3/4       |       3/4       |
| GQR7     |       3/4       |       3/4       |       3/4       |

| DSP REG  | Attempt 1       | Attempt 2       | Attempt 3       |
|----------|-----------------|-----------------|-----------------|
| 5        |      35/3       |      35/3       |      35/3       |
| 24       |      35/3       |      35/3       |      35/3       |
| 25       |      35/3       |      35/3       |      35/3       |
| 27       |      35/3       |      35/3       |      35/3       |

| AI REG   | Attempt 1       | Attempt 2       | Attempt 3       |
|----------|-----------------|-----------------|-----------------|
| 0        |     116/3       |     116/3       |     116/3       |
| 1        |     116/3       |     116/3       |     116/3       |
| 2        |     116/5593    |     116/5917    |     116/4117    |
| 3        |     116/517     |     116/11317   |     116/5593    |

| PI REG   | Attempt 1       | Attempt 2       | Attempt 3       |
|----------|-----------------|-----------------|-----------------|
| 0        |       3/3       |       3/3       |       3/3       |
| 1        |       3/3       |       3/3       |       3/3       |

</p>
</details>

I used a custom build based on [this branch](https://github.com/sepalani/dolphin/commit/c1b65471b74a52f3ca63e3ac74e2ec9266abee3c) which is really WIP but implements some kind of MMIO access with cycles adjustment based on real hardware timing. From this branch, I found that the cycles overhead is caused by the `ForceExceptionCheck` call in the `Core:Timing::ScheduleEvent` function. In this branch, the performance monitor was updated (without speed hack support) based on the downcount to see the overhead which was previously hidden by the hardcoded opinfo's cycles.

I'm open to suggestion regarding the way this fix should be implemented, especially if you've better alternative regarding the function name or its implementation.

Ready to be reviewed & tested.

2021-06-02 18:34 UTC, JMC47 commented
I checked a couple other cycle timing sensitive games in this pull request, and it doesn't seem to affect anything else.  Doesn't affect slowdown in N64 VC, doesn't fix hangs in FMVs in demo discs, doesn't affect The Daring Game for Girls, Radiant Dawn, etc.

2021-06-02 22:11 UTC, phire requested changes
Whoa... No. 

You haven't changed cycle timings at all, all you have done is scheduled an event and then told to maybe not service it until some unpredictable number of cycles later (fully dependant on what other events are happening).

If performance monitor is being updated incorrectly based on the forced exception check, (which doesn't effect actual cycles executed by dolphin, if you check timebase), then you should fix the performance monitor code, not add bugs over here.

2021-06-02 22:23 UTC, phire commented
I did warn you on IRC that the performance monitor cycles code in dolphin was buggy and incomplete. 

You should fix performance monitor before trying to fix any timing issues revealed by hwtests that read performance monitor.

2021-06-03 01:56 UTC, sepalani commented
Unless I'm totally off, the root cause of Syobon Action not booting is the fact it's stuck in some kind of interrupt/event happening too early preventing it to load its resources. I highly suspect [ForceExceptionCheck](https://github.com/dolphin-emu/dolphin/commit/2ebbfd6f856d7fad39676568529bc48f9369e103#diff-d2aeca6f94955b3772222bb77853f0dcc015b12148188cbe7e5771b42664fc7dR323) to trigger them too early. I'll try to have a MMIO timing branch ready and fix the PMC, especially for the JITs to see if it still happens. As far as my debugging went, it's spammed by these audio interrupts which prevents it to resume its normal execution.

> 
> 
> Whoa... No.
> 
> You haven't changed cycle timings at all, all you have done is scheduled an event and then told to maybe not service it until some unpredictable number of cycles later (fully dependant on what other events are happening).

My tests were run with the interpreter and the cycles were off there. If I understood the code properly, this PR should have fixed the cycles accuracy there, am I correct? Though, as you mentioned, it will delay the exception handling to a later point for the recompilers.

> 
> 
> I did warn you on IRC that the performance monitor cycles code in dolphin was buggy and incomplete.
> 
> You should fix performance monitor before trying to fix any timing issues revealed by hwtests that read performance monitor.

Yeah, that's why I used this [custom build](https://github.com/sepalani/dolphin/commit/c1b65471b74a52f3ca63e3ac74e2ec9266abee3c#diff-11cc45baa12b37c7e2e7630504d59d9b1619b12c84daa010d411fd44d1a65265R224) and the interpreter mode, which should be good for testing unless I missed something (like speedhack support which I didn't use). As you said, running this hardware test has to be done using the interpreter mode, otherwise it shows zeroes all over the place which is wrong.

@phire 
Assuming that my timing fix is sheer luck, shouldn't ForceExceptionCheck not be done if I disabled IRQ? It's another issue that I can easily fix and test.

2021-06-03 13:08 UTC, phire commented
> shouldn't ForceExceptionCheck not be done if I disabled IRQ? 

`ForceExceptionCheck` is perhaps a bad name for that function. It does both IRQs and dolphin's internal events. 

In the case of the call from `ScheduleEvent`, it's only really dealing with dolphin's internal events. 

-----

**Some background:**

`CoreTiming::Advance()` is the core of the Timing system. It checks the event queue, executes any events that are meant to be executed before or at the current cycle. It also checks for External Exceptions.

To improve performance, `CoreTiming::Advance()` is called when there is meant to be an event to execute, or an External exception to trigger an interrupt. The previous execution of `CoreTiming::Advance()` will calculate how many cycles until the next scheduled event that it knows about and sets downcounts to that value. 

A JIT slice will execute for at least `downcounts` cycles before return to Advance. Because the JIT can only end on block boundaries, it might overshoot quite a bit. 

But sometimes an MMIO access generates new events that are scheduled to execute before the current JIT slice is scheduled to end. Or an exception. In this case, `downcounts` was wrong. So `ForceExceptionCheck` actually re-calculates `downcounts` and updates it so the current slice will end early and exit. 

In the case of IRQs, it's always called with zero cycles, AKA exit as soon as possible, at the end of the current JIT block. 

But because we are dealing with events here, it can be scheduled much further into the future, or not at all if the current slice is already ending before that event.

--------------------------

> the root cause of Syobon Action not booting is the fact it's stuck in some kind of interrupt/event happening too early preventing it to load its resources. I highly suspect ForceExceptionCheck to trigger them too early

Only because `ForceExceptionCheck` has been told by someone else to trigger too early. Disabling `ForceExcpetionCheck` is kind of a brute force approach which delays ALL events all over dolphin, causing massive regressions to timings. 

What you need to do is find the exact call to `ScheduleEvent()` that has a `cycles_into_future` that is way too close. Change that and only that.

2021-09-30 16:19 UTC, sepalani commented
This PR isn't the right way to address the issue.

I'll try to find other ways (if any), based on what's already known: https://dolp.in/i12498#note-6.

2021-09-30 16:19 UTC, closed without merging