GameINI; Fix F1 2002 crash starting a race
dolphin-emu/dolphin pull request #9951
Opened 2021-07-24 14:14 UTC by Gamer64ytb

in F1 2002 when the game finishes loading to start the race it closes unexpectedly, this is because it requires having the JIT Follow Branch disabled.

2021-07-24 14:15 UTC, JMC47 commented
Jit64 or JitArm64?

2021-07-24 14:16 UTC, JosJuice commented
Have you confirmed that this crash happens when using 5.0-14731?

2021-07-24 14:16 UTC, Gamer64ytb commented
> Jit64 or JitArm64?

JITArm64

2021-07-24 14:16 UTC, Gamer64ytb commented
> Have you confirmed that this crash happens when using 5.0-14731?

Yes, crashes starting a race with JIT Follow Branch

2021-07-24 14:16 UTC, JMC47 commented
That's what I thought.  This is probably a fixable problem, so we probably shouldn't just disable the optimization.

2021-07-24 16:19 UTC, JMC47 commented
I cannot reproduce the issue.  Are you absolutely certain that you're using the latest development builds?

2021-07-24 19:56 UTC, Rumi-Larry commented
An issue report must be linked here right?

2021-07-24 20:16 UTC, JosJuice commented
> An issue report must be linked here right?

No?

2021-07-24 20:36 UTC, Rumi-Larry commented
> 
> 
> > An issue report must be linked here right?
> 
> No?

Yeah, one must be created then.

2021-07-24 21:06 UTC, JosJuice commented
No. There's no rule that you have to create an issue report for something you fix.

2021-07-24 22:50 UTC, leoetlino commented on Data/Sys/GameSettings/GF2E69.ini
> +[Core]
Could you add a comment with the GameID and the game name? Here's an example of what GameINIs should typically  look like: https://github.com/dolphin-emu/dolphin/pull/9953/files#diff-d55faa0321bd416695d7acdc9833a42e3fea60a98072b12380b3c39ec3be775eR1

2021-07-25 02:04 UTC, JMC47 requested changes
I can't approve this until I can reproduce the issue.  I need more information as the game just works for me.

2022-03-19 23:34 UTC, AdmiralCurtiss commented
JMC47 can't reproduce this and no reply from the author in 9 months, I'll just close this.

2022-03-19 23:34 UTC, closed without merging