VI: Implement post-scanout XFB output
dolphin-emu/dolphin pull request #9993
Opened 2021-08-03 23:01 UTC by Techjar

This is the more accurate way, but it adds about a frame of latency, and since most games don't change VI registers during scanout we can get away with outputting the XFB at the start of scanout. WWE Crush Hour is the (only currently known) exception, which has flickering problems when doing it this way.

This adds a path to perform the output at the end of scanout, and gates it behind an option which defaults to using the latency-reducing pre-scanout path.

I also included the appropriate INI change.

2021-08-03 23:10 UTC, iwubcode approved these changes
Code LGTM.  Untested

2021-08-03 23:11 UTC, JMC47 commented
Can't read the code, but tested.  Fixes WWE Crush Hour.

2021-08-04 02:58 UTC, phire requested changes

2021-08-04 02:58 UTC, phire commented on Source/Core/Core/HW/VideoInterface.cpp
> +  // until the end when all those changes have been collated.
Not accurate. This code-path only uses the last update to VI registers, all other updates get discarded. 

In the case of WWE Crush Hour, there is probably a tiny bit of tearing that we are not emulating. The 

    // To correctly handle that case we would need to collate all changes
    // to VI during scanout

comment from before should be preserved for future reference, but I don't really think it's worth actually implementing that just to emulate a bit of glitchyness in this one game.

2021-08-04 03:01 UTC, phire commented on Source/Core/Core/HW/VideoInterface.cpp
> +  // until the end when all those changes have been collated.
Maybe also comment to state that this still isn't accurate.

2021-08-04 03:01 UTC, phire commented
To be clear, this isn't more accurate.

It's just inaccurate in a different way that produces an acceptable result with this one game.

2021-08-04 03:03 UTC, Techjar commented on Source/Core/Core/HW/VideoInterface.cpp
> +  // until the end when all those changes have been collated.
Isn't that essentially what collating the changes is though?

2021-08-04 04:59 UTC, phire commented on Source/Core/Core/HW/VideoInterface.cpp
> +  // until the end when all those changes have been collated.
collating means collecting (and implies actually using them) rather than discarding.

Shouldn't be too hard to actually implement in a hardware implementation. Just a collect a list of  regions, with the vi properties and XFB buffers they refer to. Then issue a draw call for each region to draw that section of XFB into the final output buffer.

The rendering cost when there is only one update as expected will almost identical to the current implementation. You just pay a tiny bit of overhead for each additional region that needs to be drawn (and slightly more overhead again when a region starts outside of hblank)

But IMO, not worth implementing, unless some demoscene intro exploits it.

2021-08-04 05:00 UTC, phire approved these changes

2021-08-07 10:41 UTC, merged